---
sidebar: sidebar 
permalink: br-limitations-kubernetes.html 
keywords: limitations, known, NetApp Backup and Recovery, Kubernetes, applications, workloads 
summary: Analise estas limitações do NetApp Backup and Recovery antes de usar Backup and Recovery em seu ambiente. 
---
= Limitações conhecidas com NetApp Backup and Recovery para cargas de trabalho do Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Analise as limitações e soluções alternativas atuais para cargas de trabalho do Kubernetes em NetApp Backup and Recovery.



[[limitation-in-the-backup-and-recovery-preview-for-netapp-console-local-deployment]]
== Limitação na prévia do NetApp Backup and Recovery para implantação local do NetApp Console

Na versão prévia de Backup and Recovery para implantação local do NetApp Console, os backups para storage de objetos são suportados apenas para destinos ONTAP S3 e StorageGRID. O arquivamento de backup não é suportado nesta versão prévia.



[[changing-the-protection-policy-for-an-application]]
== Alterando a política de proteção de um aplicativo

Se você alterar a política de proteção de um aplicativo para usar um bucket diferente ou um destino de replicação secundário, a proteção pode falhar.

*Solução alternativa*: Remova o aplicativo e adicione-o novamente.



[[3-2-1-protection-policy-configuration-limitation]]
== Limitação de configuração da política de proteção 3-2-1

Se você criar uma política de proteção 3-2-1 que agende backups de storage de objetos separadamente da replicação para storage secundário, a proteção pode travar.

*Solução alternativa*: Remova o aplicativo e adicione-o novamente, e então proteja-o com uma política de proteção diferente.
