---
sidebar: sidebar 
permalink: br-limitations-kubernetes.html 
keywords: limitations, known, NetApp Backup and Recovery, Kubernetes, applications, workloads 
summary: Analise estas limitações do NetApp Backup and Recovery antes de usar Backup and Recovery em seu ambiente. 
---
= Limitações conhecidas com NetApp Backup and Recovery para cargas de trabalho do Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plataformas, dispositivos ou recursos que não funcionam ou não funcionam bem com esta versão estão listados aqui.  Leia estas limitações com atenção.



[[backup-and-recovery-preview-for-netapp-console-local-deployment-limitation]]
== Limitação da prévia do Backup and Recovery para implantação local do NetApp Console

Na versão prévia de Backup and Recovery para implantação local do NetApp Console, os backups para storage de objetos são suportados apenas para destinos ONTAP S3 e StorageGRID. O arquivamento de backup não é suportado nesta versão prévia.



[[changing-the-protection-policy-for-an-application]]
== Alterando a política de proteção de um aplicativo

Ao alterar a política de proteção associada a um aplicativo para usar um bucket diferente ou um destino de replicação secundário, a política de proteção pode falhar.

*Solução alternativa*: remova e adicione novamente o aplicativo.



[[3-2-1-protection-policy-configuration-limitation]]
== Limitação de configuração da política de proteção 3-2-1

Ao criar uma política de proteção 3-2-1 em que nenhum backup de storage de objetos ocorre ao mesmo tempo que a replicação para storage secundário, a política de proteção trava ao proteger o aplicativo.

*Solução alternativa*: Remova e adicione novamente o aplicativo e proteja-o com uma política de proteção diferente.
