---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versão do NetApp Backup and Recovery tem as seguintes limitações conhecidas. 
---
= Limitações conhecidas do NetApp Backup and Recovery para cargas de trabalho KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plataformas, dispositivos ou recursos que não funcionam ou não funcionam bem com esta versão estão listados aqui.  Leia estas limitações com atenção.

As seguintes ações e configurações não são suportadas na versão de visualização privada das cargas de trabalho do KVM no NetApp Backup and Recovery:



== Ações não suportadas

As seguintes ações não são suportadas na versão de visualização privada:

* Clonar, montar ou desmontar VMs
* Restaurar VMs para um local alternativo
* Proteja VMs armazenadas em SAN
* Proteger aplicativos
* Backup ou restauração de armazenamentos de objetos
* Editar grupos de proteção
* Crie grupos de proteção usando VMs de vários hosts KVM
* Crie backups definidos pelo usuário (somente backups iniciados no NetApp Console são suportados)




== Configurações não suportadas

As seguintes configurações não são suportadas:

* Controle de acesso baseado em função (RBAC)
* Discos diretamente conectados ao host KVM
* Discos distribuídos por vários pontos de montagem ou compartilhamentos NFS
* Formato de disco RAW
* Tipos de pool de armazenamento diferentes de NetFS (somente NetFS é suportado)

