---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versão do NetApp Backup and Recovery tem as seguintes limitações conhecidas. 
---
= Limitações conhecidas do NetApp Backup and Recovery para cargas de trabalho KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plataformas, dispositivos ou recursos que não funcionam ou não funcionam bem com esta versão estão listados aqui.  Leia estas limitações com atenção.

As seguintes ações e configurações não são suportadas em cargas de trabalho KVM no NetApp Backup and Recovery:



== Ações não suportadas

As seguintes ações não são suportadas:

* Clonar, montar ou desmontar VMs
* Restaurar VMs para um local alternativo
* Proteja VMs armazenadas em SAN
* Proteger aplicativos
* Crie backups definidos pelo usuário (somente backups iniciados no NetApp Console são suportados)




== Configurações não suportadas

As seguintes configurações não são suportadas:

* Controle de acesso baseado em função (RBAC)
* Discos diretamente conectados ao host KVM
* Discos distribuídos por vários pontos de montagem ou compartilhamentos NFS
* Formato de disco RAW
* Tipos de pool de armazenamento diferentes de NetFS (somente NetFS é suportado)




== Notas de resolução de problemas

Observe o seguinte ao usar cargas de trabalho KVM com NetApp Backup and Recovery.

* Os backups podem falhar se o QEMU Guest Agent não estiver em execução em uma VM protegida. Como solução alternativa, certifique-se de que o  `qemu-guest-agent` daemon esteja em execução na VM antes de iniciar o backup.

