---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: O NetApp Backup and Recovery precisa primeiro descobrir dados para que você possa usar o serviço.  Durante a descoberta, o NetApp Backup and Recovery analisa todos os volumes e arquivos nos sistemas da sua organização. 
---
= Limitações conhecidas com o NetApp Backup and Recovery para cargas de trabalho do Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plataformas, dispositivos ou recursos que não funcionam ou não funcionam bem com esta versão estão listados aqui.  Leia estas limitações com atenção.



== Ações não suportadas

As seguintes ações não são suportadas na versão de visualização privada das cargas de trabalho do Hyper-V no NetApp Backup and Recovery:

* Crie grupos de recursos usando máquinas virtuais de vários hosts Hyper-V.
* Restaurar VMs para um local alternativo
* Discos de abrangência (em vários compartilhamentos CIFS)
* Proteja VMs em SAN
* Editar grupos de proteção
* Proteja hosts Hyper-V agrupados usando o System Center Virtual Machine Manager (SCVMM)




== Contas legadas do NetApp Console sem suporte

Contas legadas do NetApp Console não oferecem suporte aos recursos necessários para proteger cargas de trabalho do Hyper-V.  Verifique se você está usando uma conta legada na interface da Web do Console.  Se você tiver uma conta de console legada, crie uma nova conta antes de proteger as cargas de trabalho do Hyper-V.

.Passos
. No menu do NetApp Console , selecione *Administração > Identidade e acesso*.
. Em *Organização*, verifique se um *ID da conta* é exibido ao lado do ID da organização.
+
Se um *ID de conta* for exibido, você está usando uma conta legada.

. Se você estiver usando uma conta legada, faça o seguinte:
+
.. Saia do Console e navegue até o https://console.netapp.com/["Página de login do console"^] .
.. Selecione *Inscrever-se* para criar uma nova conta.



