---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: Esta versão do NetApp Backup and Recovery tem as seguintes limitações conhecidas. 
---
= Limitações conhecidas do NetApp Backup and Recovery para cargas de trabalho KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Analise as limitações atuais para cargas de trabalho KVM em NetApp Backup and Recovery.

As seguintes ações e configurações não suportadas se aplicam a cargas de trabalho KVM em NetApp Backup and Recovery:



[[unsupported-actions]]
== Ações não suportadas

As seguintes ações não são suportadas:

* Na versão prévia de Backup and Recovery para implantação local do NetApp Console, os backups para storage de objetos são suportados apenas para destinos ONTAP S3 e StorageGRID. O arquivamento de backup não é suportado nesta versão prévia.
* Clonar, montar ou desmontar VMs
* Proteja VMs armazenadas em SAN
* Proteger aplicativos
* Crie backups definidos pelo usuário (somente backups iniciados no NetApp Console são suportados)




[[unsupported-configurations]]
== Configurações não suportadas

As seguintes configurações não são suportadas:

* Controle de acesso baseado em função (RBAC)
* Discos diretamente conectados ao host KVM
* Discos distribuídos por vários pontos de montagem ou compartilhamentos NFS
* Formato de disco RAW
* Tipos de pool de armazenamento diferentes de NetFS (somente NetFS é suportado)




[[troubleshooting-notes]]
== Notas de resolução de problemas

Observe o seguinte ao usar cargas de trabalho KVM com o NetApp Backup and Recovery.

* Os backups podem falhar se o Agente Convidado do QEMU não estiver em execução em uma VM protegida. Para evitar esse problema, certifique-se de que o  `qemu-guest-agent` daemon esteja em execução na VM antes de iniciar o backup.

