---
sidebar: sidebar 
permalink: br-rbac-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: Para aumentar a segurança, configure o acesso para funções específicas no NetApp Backup e Recovery. 
---
= Configurar controle de acesso baseado em funções no NetApp Backup e Restauração
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configure o controle de acesso baseado em funções (RBAC) no NetApp Console para controlar quem pode acessar os recursos do NetApp Backup and Recovery. Você pode atribuir funções administrativas ou de visualizador a cargas de trabalho que suportam RBAC. As cargas de trabalho que ainda não suportam RBAC permanecem acessíveis a todos os usuários com funções de backup e recuperação até que a associação em nível de projeto ou de frota esteja disponível.


NOTE: NetApp Console usa projetos para organizar recursos em pastas, enquanto NetApp Console implantação local se refere a projetos como frotas.

Para controlar o acesso aos recursos da sua organização, conclua estas etapas na página *Administração > Identidade e acesso* do NetApp Console.


NOTE: Esses passos pressupõem que você tenha a função de administrador da organização no NetApp Console.

.Passos
. Crie a estrutura do projeto de identidade e acesso.
+
Como administrador da organização, configure a estrutura de pastas e projetos onde as cargas de trabalho vão residir.

. Atribuir funções de usuário.
+
.. Opção principal:
+
Adicione usuários a cada projeto designado para cargas de trabalho e atribua a eles a função apropriada. Por exemplo:

+
*** *Administrador da organização* e *superadministrador de Backup and Recovery*: um usuário com essas funções pode visualizar todos os recursos em todas as organizações, além de descobrir cargas de trabalho do Backup and Recovery e atribuí-las a projetos (por exemplo, US East ou US West).
*** *Administrador de pasta ou projeto* e *superadministrador de NetApp Backup and Recovery*: Um usuário com essas funções pode visualizar apenas os recursos em sua pasta ou projeto atribuído, mas pode descobrir cargas de trabalho do NetApp Backup and Recovery e atribuí-las a esse projeto.


.. Opção alternativa:
+
Em vez de conceder a um usuário acesso administrativo completo ao Backup and Recovery, você pode atribuir a si mesmo a função de superadministrador de Backup and Recovery e descobrir as workloads diretamente.



. Descubra cargas de trabalho em Backup and Recovery.
+
Os administradores da organização, de pastas ou de projetos descobrem as cargas de trabalho disponíveis e selecionam o projeto apropriado (como US East ou US West). Cada carga de trabalho é automaticamente associada ao projeto selecionado.

. Adicionar usuários aos projetos.
+
Administradores da organização, de pastas ou de projetos adicionam usuários do NetApp Console a projetos com cargas de trabalho. Atribua aos usuários a função de visualizador da organização e uma função de Backup and Recovery com base nas necessidades de acesso deles. Usuários com a função apropriada de Backup and Recovery obtêm acesso automaticamente a novas cargas de trabalho nesses projetos.





[[related-information]]
== Informações relacionadas

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["Saiba mais sobre o gerenciamento de identidade e acesso do NetApp Console"^].
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Funções de NetApp Backup and Recovery no ​​NetApp Console"^].

