---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: O NetApp Backup and Recovery precisa primeiro descobrir as cargas de trabalho para que você possa protegê-las. 
---
= Descubra as cargas de trabalho do Oracle Database em NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A descoberta de bancos de dados Oracle permite que NetApp Backup and Recovery os proteja criando e restaurando backups e snapshots.

*Função de console necessária* Superadministrador de backup e recuperação.  Aprenda sobrelink:reference-roles.html["Funções e privilégios de backup e recuperação"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .



== Adicione um host do Oracle Database e descubra recursos

Adicione informações do host Oracle e deixe o NetApp Backup and Recovery descobrir cargas de trabalho. Em cada agente do Console, selecione os sistemas onde você deseja descobrir cargas de trabalho.

.Passos
. No menu do NetApp Console , selecione *Proteção > Backup e recuperação*.
. Em *Cargas de trabalho*, selecione o bloco *Oracle*.
. Selecione *Descobrir recursos*.
. Selecione *Oracle* para o campo *Tipo de carga de trabalho*.
. Se você ainda não armazenou credenciais para este host Oracle Database, selecione *Adicionar credenciais*.
+
.. Selecione o agente do Console a ser usado com este host.
.. Digite um nome para esta credencial.
.. Digite o nome de usuário e a senha da conta.
.. Selecione *Concluído*.


. *Registro do host*: Adicione um novo host do Oracle Database. No campo *Nome de domínio totalmente qualificado (FQDN) ou endereço IP do host*, insira o FQDN ou endereço IP do host – para bancos de dados em cluster, você pode inserir o FQDN ou IP de qualquer nó do cluster. Em seguida, forneça as credenciais, o agente do Console e o número da porta.
. (Opcional) Se você escolher credenciais para um usuário que não seja root, faça o seguinte:
+
.. Para obter instruções sobre como adicionar o usuário não root que você selecionou ao arquivo sudoers no host do Oracle Database, selecione *Configurar sudoers*.
.. Siga as instruções na caixa de diálogo, marque a caixa de seleção quando terminar e selecione *Done*.


. *Configurações avançadas*: faça o seguinte:
+
.. Insira a porta e o caminho de instalação a serem usados para o NetApp plug-in. O plug-in permite a comunicação entre o host do Oracle Database e NetApp Backup and Recovery.
.. Escolha se deseja permitir que o NetApp Backup e recuperação instale o plug-in automaticamente em cada host ou ignorar a instalação automática do plug-in para todos os hosts. Selecione *Mostrar como* para obter instruções de instalação manual.
+
[NOTE]
====
O NetApp Backup and Recovery se conecta a cada host via SSH para instalar o plug-in automaticamente. Habilite *Usar instalação manual* quando qualquer uma das seguintes condições se aplicar:

*** Um ou mais hosts não estão executando o serviço SSH.
*** Qualquer host já possui o NetApp plug-in (inclusive se apenas alguns membros do cluster o tiverem).
*** Você prefere instalar o plug-in em cada host manualmente.


====
.. Se o host do banco de dados estiver em cluster, habilite a opção *Adicionar todos os hosts no cluster* para descobrir todos os hosts no cluster.
.. Escolha se deseja executar verificações de pré-instalação em cada host antes de instalar automaticamente o plug-in. Se as verificações falharem, a instalação automática do plug-in será interrompida. Para ignorar as verificações e instalar mesmo assim, habilite *Ignorar verificações de pré-instalação opcionais* (habilitado automaticamente se você escolher instalação manual).


. Selecione *Descobrir*.
+

TIP: A adição de recursos pode levar vários minutos. Para ver o progresso, selecione *Acompanhar progresso* na caixa de diálogo de status na parte inferior da página de Inventário ou selecione *Monitoramento* no menu à esquerda.



.Resultado
A carga de trabalho do Oracle Database é exibida na lista de cargas de trabalho na página de Inventory.



== Continue para o Painel de NetApp Backup and Recovery

. No menu do NetApp Console , selecione *Proteção* > *Backup e recuperação*.
. Selecione um bloco de carga de trabalho (por exemplo, Microsoft SQL Server).
. No menu Backup e Recuperação, selecione *Painel*.
. Revise a saúde da proteção de dados.  O número de cargas de trabalho em risco ou protegidas aumenta com base nas cargas de trabalho recém-descobertas, protegidas e armazenadas em backup.

