---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Use o NetApp Console para efetuar login no serviço NetApp Backup and Recovery . 
---
= Efetue login no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Faça login no NetApp Backup and Recovery a partir do NetApp Console para descobrir cargas de trabalho e gerenciar operações de proteção.

O NetApp Backup and Recovery usa gerenciamento de identidade e acesso para controlar o que cada usuário pode fazer.

Para obter detalhes sobre as ações que cada função pode executar, consultelink:reference-roles.html["Funções de usuário do NetApp Backup and Recovery"] .

Para fazer login no NetApp Console, você pode usar suas credenciais do NetApp Support Site ou pode se cadastrar para obter uma conta do NetApp Console usando seu endereço de e-mail e uma senha. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Saiba mais sobre como fazer login"^].

*Função necessária do NetApp Console* Superadministrador de backup e recuperação ou administrador de restauração de backup e recuperação. Se você estiver protegendo dados armazenados em um cluster Cloud Volumes ONTAP, a função de administrador do Cloud Volumes ONTAP também é necessária. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^]

Para adicionar um agente do Console, você precisa ter a função de superadministrador do Backup and Recovery.

.Passos
. Faça um dos seguintes:
+
** Se você estiver usando o NetApp Console, abra um navegador da web e acesse o  https://console.netapp.com/["NetApp Console"^].
** Se você estiver usando a implantação local do NetApp Console, abra um navegador da web e acesse o endereço IP da interface web da sua implantação local do Console.
+
A página de login do NetApp Console é exibida.



. Efetue login no Console.
. Na navegação à esquerda do Console, selecione *Proteção* > *Backup e Recuperação*.
+
** Se esta for a sua primeira vez acessando o NetApp Backup and Recovery e você ainda não adicionou um sistema à página *Sistemas*, o serviço de backup e recuperação exibe a página inicial "Bem-vindo ao novo NetApp Backup and Recovery" com uma opção para adicionar um sistema. Para obter detalhes sobre como adicionar um sistema à página *Sistemas*, consulte  https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introdução ao modo padrão do NetApp Console"^].
** Se você estiver acessando o Backup and Recovery pela primeira vez e tiver um sistema no Console, mas nenhum recurso descoberto, a página _Bem-vindo ao novo NetApp Backup and Recovery_ será exibida com uma opção para *Descobrir recursos*.


. Se ainda não fez isso, selecione *Descobrir e gerenciar*.
+
** Para cargas de trabalho do Microsoft SQL Server, consulte link:br-start-discover.html["Descubra as cargas de trabalho do Microsoft SQL Server"].
** Para cargas de trabalho VMware, consulte link:br-use-vmware-discovery.html["Descubra as cargas de trabalho da VMware"].
** Para cargas de trabalho KVM, consulte link:br-start-discover-kvm.html["Descubra cargas de trabalho KVM"].
** Para cargas de trabalho do Oracle Database, consulte link:br-start-discover-oracle.html["Descubra cargas de trabalho do Oracle Database"].
** Para cargas de trabalho do Hyper-V, consulte link:br-start-discover-hyperv.html["Descubra as cargas de trabalho do Hyper-V"].
** Para cargas de trabalho do Kubernetes, consulte link:br-start-discover-kubernetes.html["Descubra as cargas de trabalho do Kubernetes"].



