---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: O NetApp Backup and Recovery precisa primeiro descobrir as cargas de trabalho para que você possa protegê-las. 
---
= Descubra cargas de trabalho KVM no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubra hosts KVM e máquinas virtuais no NetApp Backup and Recovery para que você possa protegê-los com políticas de proteção. Seu ambiente KVM deve ser gerenciado por uma plataforma de gerenciamento, como o Apache CloudStack, antes da descoberta.

*Função necessária do NetApp Console* superadministrador de backup e recuperação. Saiba mais sobre link:reference-roles.html["Funções e privilégios de backup e recuperação"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].



[[add-a-management-platform-kvm-host-and-discover-resources]]
== Adicione uma plataforma de gerenciamento, um host KVM e descubra recursos.

Adicione informações sobre a plataforma de gerenciamento e o host KVM e permita que o NetApp Backup and Recovery descubra as cargas de trabalho.


NOTE: Após adicionar um sistema de storage ao NetApp Console, aguarde alguns minutos antes de descobrir os recursos. Descobrir recursos imediatamente após adicionar um sistema de storage pode fazer com que a descoberta falhe.

.Passos
. No menu do NetApp Console , selecione *Proteção* > *Backup e recuperação*.
. Em *Cargas de trabalho*, selecione o bloco *KVM*.
. Selecione *Descobrir recursos*.
. Insira as seguintes informações:
+
.. *Tipo de carga de trabalho*: Selecione *KVM*.
.. Se você ainda não integrou sua plataforma de gerenciamento com o Backup e Recuperação, selecione *Adicionar plataforma de gerenciamento*.
+
... Insira as seguintes informações:
+
**** *Endereço IP ou FQDN da plataforma de gerenciamento*: insira o endereço IP ou um FQDN da plataforma de gerenciamento.
**** *Chave de API*: Insira a chave de API a ser usada para autenticar as solicitações de API.
**** *Chave secreta*: Insira a chave secreta a ser usada para autenticar as solicitações da API.
**** *Porta*: Insira a porta a ser usada para comunicação entre o Backup e Recuperação e a plataforma de gerenciamento.
**** *Agentes*: Selecione um agente de console para facilitar a comunicação entre o Backup e Recuperação e a plataforma de gerenciamento.


... Ao terminar, selecione *Adicionar*.


.. *Configurações do KVM*: Faça o seguinte:
+
... Se você ainda não armazenou credenciais para este host KVM, selecione *Adicionar credenciais*.
+
**** Selecione o agente do Console a ser usado com este host.
**** Digite um nome para esta credencial.
**** Digite o nome de usuário e a senha da conta.
**** Selecione *Concluído*.


... Adicione um novo host KVM inserindo as seguintes informações:
+
**** *Nome de domínio totalmente qualificado (FQDN) ou endereço IP do KVM*: Insira o FQDN ou o endereço IP do host.
**** *Agentes*: Selecione o agente do Console a ser usado para comunicação entre o NetApp Backup and Recovery e o host KVM.
**** *Credenciais*: selecione uma credencial armazenada para o host KVM.




.. *Configurações avançadas*: Opcionalmente, insira uma porta para se comunicar com o host KVM e selecione a plataforma de gerenciamento do host na lista.


. Selecione *Descobrir*.
+

TIP: Este processo pode levar alguns minutos.



.Resultado
A carga de trabalho do KVM é exibida na lista de cargas de trabalho na página Inventário.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continue para o Painel de NetApp Backup and Recovery

.Passos
. No menu do NetApp Console , selecione *Proteção* > *Backup e recuperação*.
. Selecione o bloco de carga de trabalho KVM.
. No menu Backup e Recuperação, selecione *Painel*.
. Revise a saúde da proteção de dados.  O número de cargas de trabalho em risco ou protegidas aumenta com base nas cargas de trabalho recém-descobertas, protegidas e armazenadas em backup.

