---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions 
summary: Estas perguntas frequentes podem ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Estas perguntas frequentes podem ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta.



== Implantação

*Você precisa de uma licença para usar a versão de visualização do NetApp Backup and Recovery?*

Você pode usar os seguintes tipos de licença:

* Inscreva-se para um teste gratuito de 30 dias.


*Como você habilita o NetApp Backup and Recovery?*  O NetApp Backup and Recovery não requer nenhuma ativação.  A opção de backup e recuperação é ativada automaticamente na navegação à esquerda do Console.

Para começar, você precisa se inscrever ou entrar em contato com seu representante de vendas da NetApp para experimentar o Backup e Recuperação. Então, quando você usar o agente do Console, ele incluirá os recursos apropriados para o serviço.

Para começar a usar o NetApp Backup and Recovery, selecione "Começar a descobrir cargas de trabalho" na página inicial.

* O NetApp Backup and Recovery está disponível nos modos padrão, restrito e privado?*  No momento, o NetApp Backup and Recovery está disponível apenas no modo padrão.  Fique ligado para mais informações.

Para obter uma explicação sobre esses modos em todos os serviços de dados da NetApp , consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"^] .



== Acesso

*Qual é o URL do NetApp Backup and Recovery?* Para o URL, em um navegador, digite: https://console.netapp.com/["https://console.netapp.com/backup-and-recovery"^] para acessar o NetApp Console.

*Como as permissões de acesso são gerenciadas?*  Somente os administradores da organização têm a capacidade de iniciar o serviço e descobrir cargas de trabalho (porque isso envolve o compromisso de uso de um recurso).  Interações subsequentes podem ser feitas por qualquer função.

*Qual é a melhor resolução do dispositivo?*  A resolução de dispositivo recomendada para o NetApp Backup and Recovery é 1920x1080 ou melhor.

*Qual navegador devo usar?* Qualquer navegador moderno funcionará.



== Interação com outros serviços

* O NetApp Backup and Recovery está ciente das configurações de proteção feitas no NetApp ONTAP?*  Sim, o NetApp Backup and Recovery descobre agendamentos de snapshots definidos no ONTAP.

*Se você definir uma política usando o NetApp Backup and Recovery, precisará fazer alterações futuras somente no Backup and Recovery?* Recomendamos que você faça alterações de política no NetApp Backup and Recovery.



== Cargas de trabalho

*O que compõe uma carga de trabalho?*  Uma carga de trabalho é um aplicativo para a versão Preview 2025.  Uma carga de trabalho inclui todos os volumes usados por uma única instância do aplicativo.  Por exemplo, uma instância de banco de dados do Microsoft SQL Server implantada em mssql3.host.com pode ter vol1 e vol2 para seus dados e logs, respectivamente.  Esses volumes juntos constituem a carga de trabalho para aquela instância específica da instância do banco de dados.

*Quais cargas de trabalho o NetApp Backup and Recovery suporta?*

Para a versão Preview 2025, o NetApp Backup and Recovery pode identificar as seguintes cargas de trabalho: aplicativos do Microsoft SQL Server.

*O que é uma carga de trabalho "protegida"?*  No NetApp Backup and Recovery, uma carga de trabalho mostra um status "protegida" quando tem uma política de detecção primária ativada.

*O que é uma carga de trabalho "em risco"?*  Se uma carga de trabalho não tiver uma política de detecção primária habilitada, ela estará "em risco", mesmo que tenha uma política de backup e snapshot habilitada.

*Nova carga de trabalho adicionada, mas ainda não aparece* Se você adicionou uma nova carga de trabalho ao seu ambiente, inicie a descoberta novamente e aplique políticas de proteção para proteger esse novo recurso.



== Políticas de proteção

* O NetApp Backup and Recovery está ciente das configurações de proteção feitas no NetApp ONTAP?*

Sim, o NetApp Backup and Recovery descobre agendamentos de snapshots definidos no ONTAP e se ARP e FPolicy estão habilitados em uma carga de trabalho descoberta.  As informações que você vê inicialmente no Painel são agregadas de outras soluções e produtos da NetApp .

* O NetApp Backup and Recovery está ciente das políticas já definidas no SnapCenter?*

Sim, se você tiver cargas de trabalho gerenciadas no SnapCenter, as políticas gerenciadas por esses produtos serão trazidas para o NetApp Backup and Recovery.

*Você pode modificar as políticas transferidas do SnapCenter?*

Sim, você pode modificar políticas que foram gerenciadas pelo SnapCenter no NetApp Backup and Recovery.

*Se existirem políticas do ONTAP (já habilitadas no System Manager, como ARP, FPolicy e snapshots), elas serão alteradas no NetApp Backup and Recovery?*

Não. O NetApp Backup and Recovery não modifica nenhuma política de detecção existente (configurações ARP, FPolicy) do ONTAP.

*O que acontece se você adicionar novas políticas no SnapCenter após se inscrever no NetApp Backup and Recovery?*

O NetApp Backup and Recovery reconhece quaisquer novas políticas criadas no SnapCenter.

*Você pode alterar as políticas do ONTAP?*

Sim, você pode alterar políticas do ONTAP no NetApp Backup and Recovery.  Você também pode criar novas políticas no NetApp Backup and Recovery e aplicá-las às cargas de trabalho.  Esta ação substitui as políticas ONTAP existentes pelas políticas criadas no NetApp Backup and Recovery.
