---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Use o NetApp Console para efetuar login no serviço NetApp Backup and Recovery . 
---
= Efetue login no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use o NetApp Console para efetuar login no NetApp Backup and Recovery.

O NetApp Backup and Recovery usa gerenciamento de identidade e acesso para controlar o que cada usuário pode fazer.

Para obter detalhes sobre as ações que cada função pode executar, consultelink:reference-roles.html["Funções de usuário do NetApp Backup and Recovery"] .

Para efetuar login no NetApp Console, você pode usar suas credenciais do site de suporte da NetApp ou pode se inscrever para um login no NetApp Console usando seu e-mail e uma senha. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Saiba mais sobre como fazer login"^] .

*Função necessária do NetApp Console * Superadministrador de backup e recuperação ou função de administrador de restauração de backup e recuperação. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .

Para adicionar um agente do Console, você precisa ter a função de superadministrador do Backup and Recovery.

.Passos
. Abra um navegador da web e vá para o https://console.netapp.com/["NetApp Console"^] .
+
A página de login do NetApp Console é exibida.

. Efetue login no Console.
. Na navegação à esquerda do Console, selecione *Proteção* > *Backup e Recuperação*.
+
** Se esta for a sua primeira vez a iniciar sessão no Backup and Recovery e ainda não tiver adicionado um sistema à página *Sistemas*, o Backup and Recovery apresenta a página inicial "Bem-vindo ao novo NetApp Backup and Recovery" com uma opção para adicionar um sistema. Para obter detalhes sobre como adicionar um sistema à página *Sistemas*, consulte https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introdução ao modo padrão do NetApp Console"^].
** Se você estiver acessando o Backup and Recovery pela primeira vez e tiver um sistema no Console, mas nenhum recurso descoberto, a página _Bem-vindo ao novo NetApp Backup and Recovery_ será exibida com uma opção para *Descobrir recursos*.


. Se você ainda não fez isso, selecione a opção *Descobrir e gerenciar*.
+
** Para cargas de trabalho do Microsoft SQL Server, consultelink:br-start-discover.html["Descubra as cargas de trabalho do Microsoft SQL Server"] .
** Para cargas de trabalho VMware, consultelink:br-use-vmware-discovery.html["Descubra as cargas de trabalho da VMware"] .
** Para cargas de trabalho KVM, consultelink:br-start-discover-kvm.html["Descubra cargas de trabalho KVM"] .
** Para cargas de trabalho do Oracle Database, consulte link:br-start-discover-oracle.html["Descubra cargas de trabalho do Oracle Database"].
** Para cargas de trabalho do Hyper-V, consultelink:br-start-discover-hyperv.html["Descubra as cargas de trabalho do Hyper-V"] .
** Para cargas de trabalho do Kubernetes, consultelink:br-start-discover-kubernetes.html["Descubra as cargas de trabalho do Kubernetes"] .



