---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: O NetApp Backup and Recovery precisa descobrir máquinas virtuais Hyper-V antes que você possa protegê-las. 
---
= Descubra as cargas de trabalho do Hyper-V no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Backup and Recovery precisa descobrir máquinas virtuais Hyper-V antes que você possa protegê-las.

*Função de console necessária* Superadministrador de backup e recuperação.  Aprenda sobrelink:reference-roles.html["Funções e privilégios de backup e recuperação"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .



== Adicionar um host Hyper-V e descobrir recursos

Adicione informações do host Hyper-V e deixe o NetApp Backup and Recovery descobrir máquinas virtuais.  Em cada agente do Console, selecione os sistemas onde você deseja descobrir os recursos.


NOTE: Quando você adiciona hosts Hyper-V e descobre recursos, o NetApp Backup and Recovery instala o plug-in NetApp Hyper-V e o plug-in NetApp SnapCenter Windows FileSystem no host Hyper-V para ajudar a gerenciar e proteger máquinas virtuais.

.Passos
. No menu do NetApp Console , selecione *Proteção* > *Backup e recuperação*.
+
Se esta for a primeira vez que você faz login no NetApp Backup and Recovery, você já tem um sistema no Console, mas não descobriu nenhum recurso. A página inicial "Bem-vindo ao novo NetApp Backup and Recovery" aparece e mostra uma opção para *Descobrir recursos*.

. Selecione *Descobrir recursos*.
. Insira as seguintes informações:
+
.. *Tipo de carga de trabalho*: Selecione *Hyper-V*.
.. Se você ainda não armazenou credenciais para este host Hyper-V, selecione *Adicionar credenciais*.
+
... Selecione o agente do Console a ser usado com este host.
... Digite um nome para esta credencial.
... Digite o nome de usuário e a senha da conta.
... Selecione *Concluído*.


.. *Registro de host*: Adicione um novo host Hyper-V.  Insira o FQDN ou endereço IP do host, credenciais, agente do console e número da porta.


. Selecione *Descobrir*.
+

TIP: Este processo pode levar alguns minutos.



.Resultado
Depois que o NetApp Backup and Recovery descobre recursos, a página Inventário exibe a carga de trabalho do Hyper-V na lista de cargas de trabalho.



== Continue para o Painel de NetApp Backup and Recovery

.Passos
. No menu do NetApp Console , selecione *Proteção* > *Backup e recuperação*.
. Selecione um bloco de carga de trabalho (por exemplo, Microsoft SQL Server).
. No menu Backup e Recuperação, selecione *Painel*.
. Revise a saúde da proteção de dados.  O número de cargas de trabalho em risco ou protegidas aumenta com base nas cargas de trabalho recém-descobertas, protegidas e armazenadas em backup.

