---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: O NetApp Backup and Recovery precisa primeiro descobrir as cargas de trabalho para que você possa usar o serviço. 
---
= Descubra cargas de trabalho do Kubernetes no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Backup and Recovery precisa descobrir cargas de trabalho do Kubernetes antes de protegê-las.

*Função necessária do NetApp Console* superadministrador de backup e recuperação. Se você estiver protegendo dados armazenados em um cluster Cloud Volumes ONTAP, a função Cloud Volumes ONTAP Admin também é necessária. Saiba mais sobre link:reference-roles.html["Funções e privilégios de backup e recuperação"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].



[[discover-kubernetes-workloads]]
== Descubra as cargas de trabalho do Kubernetes

No inventário de Backup and Recovery, descubra cargas de trabalho do Kubernetes em seu ambiente. Adicionar uma carga de trabalho adiciona um cluster do Kubernetes ao NetApp Backup and Recovery. Em seguida, você pode adicionar aplicativos e proteger os recursos do cluster. Opcionalmente, você pode descobrir recursos locais do Kubernetes isolados da internet usando a implantação local do NetApp Console.

[NOTE]
====
Ao descobrir um cluster que está atualmente protegido com Trident Protect, quaisquer agendamentos de backup usados com Trident Protect são desativados durante o processo de descoberta (os agendamentos de backup do Trident Protect não são compatíveis com Backup and Recovery). Para proteger os aplicativos do cluster, link:br-use-policies-create.html["crie uma nova política de proteção"] ou associe os aplicativos a uma política existente. Você pode então remover os agendamentos de backup do Trident Protect, se necessário.

====
.Passos
. Faça um dos seguintes:
+
** Se você estiver descobrindo cargas de trabalho do Kubernetes pela primeira vez, no NetApp Backup and Recovery, em *Cargas de trabalho*, selecione o bloco *Kubernetes*.
** Se você já descobriu cargas de trabalho do Kubernetes, no NetApp Backup and Recovery, selecione *Inventário* > *Cargas de trabalho* e, em seguida, selecione *Descobrir recursos*.


. Selecione o tipo de carga de trabalho *Kubernetes*.
. Insira um nome de cluster e escolha um agente de Console para usar com o cluster.
+
O NetApp Backup and Recovery fornece instruções que variam de acordo com o tipo de instalação que você seleciona. Se você usar a implantação local do NetApp Console, poderá escolher instruções que permitem descobrir recursos isolados, sem conectividade de rede externa.

. Escolha um tipo de instalação para visualizar as instruções para instalar o Trident Protect no seu cluster Kubernetes:
+
** Selecione *Conectado* para descobrir clusters que possuem conectividade de rede externa.
** Selecione *Isolado da rede* para descobrir clusters que não possuem conectividade de rede externa.
+
[role="tabbed-block"]
====
.Descoberta conectada
--
... Siga as instruções da linha de comando que aparecem no NetApp Backup and Recovery. Essas etapas garantem que o NetApp Backup and Recovery possa interagir com o cluster.


--
.Descoberta air-gapped
--
... Insira a URL do seu registro de contêineres Docker privado. Esse registro é usado para baixar as imagens do Trident Protect e do Trident Protect Connector durante a instalação.
... Se o seu registro de contêineres privado exigir autenticação, use um dos seguintes métodos para configurar as credenciais do registro:
+
**** *Autenticação no nível do nó*: Configure as credenciais de registro no ambiente de execução do contêiner em cada nó. Uma vez configurado, todos os pods podem baixar imagens sem a necessidade de configurações adicionais do Helm.
**** *Segredo para extrair imagens do Kubernetes*: Crie um segredo para extrair imagens do Kubernetes no  `trident-protect` namespace e, em seguida, faça referência a ele durante a etapa de atualização do Helm nas instruções de instalação do Trident Protect:
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Siga as instruções da linha de comando que aparecem no NetApp Backup and Recovery, adicionando as informações do segredo de pull da imagem durante a etapa do Helm (se necessário). Essas etapas garantem que o NetApp Backup and Recovery possa interagir com o cluster.


--
====


. Após concluir as etapas de instalação do Trident Protect, selecione *Descobrir*.
+
O cluster é adicionado ao inventário.

. Selecione *Exibir* na carga de trabalho do Kubernetes associada para ver a lista de aplicativos, clusters e namespaces para essa carga de trabalho.




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continue para o Painel de NetApp Backup and Recovery

Siga estas etapas para visualizar o Painel de NetApp Backup and Recovery .

. No menu do NetApp Console , selecione *Proteção* > *Backup e recuperação*.
. Selecione o bloco de carga de trabalho do Kubernetes.
. No menu Backup e Recuperação, selecione *Painel*.
. Revise a saúde da proteção de dados.  O número de cargas de trabalho em risco ou protegidas aumenta com base nas cargas de trabalho recém-descobertas, protegidas e armazenadas em backup.
+
link:br-use-dashboard.html["Saiba o que o Painel mostra para você"].


