---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: O NetApp Backup and Recovery precisa descobrir máquinas virtuais Hyper-V antes que você possa protegê-las. 
---
= Descubra as cargas de trabalho do Hyper-V no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubra máquinas virtuais Hyper-V no NetApp Backup and Recovery para que você possa protegê-las com políticas de proteção.

*Função necessária do NetApp Console* superadministrador de backup e recuperação. Saiba mais link:reference-roles.html["Funções e privilégios de backup e recuperação"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].



[[add-a-hyper-v-host-and-discover-resources]]
== Adicionar um host Hyper-V e descobrir recursos

Adicione informações do host Hyper-V para permitir que o NetApp Backup and Recovery descubra máquinas virtuais. Em cada agente do Console, selecione os sistemas nos quais você deseja descobrir recursos.


NOTE: Após adicionar um sistema de storage ao NetApp Console, aguarde alguns minutos antes de descobrir os recursos. Descobrir recursos imediatamente após adicionar um sistema de storage pode fazer com que a descoberta falhe.


NOTE: Quando você adiciona hosts Hyper-V e descobre recursos, o NetApp Backup and Recovery instala o plug-in NetApp Hyper-V e o plug-in NetApp SnapCenter Windows FileSystem no host Hyper-V para ajudar a gerenciar e proteger máquinas virtuais.

.Passos
. No menu NetApp Console, selecione *Proteção* > *Backup e Recuperação*.
+
Se esta for a sua primeira vez acessando o NetApp Backup and Recovery e você já tiver um sistema na Console, mas ainda não tiver descoberto recursos, a página inicial "Bem-vindo ao novo NetApp Backup and Recovery" será exibida com uma opção para *Descobrir recursos*.

. Selecione *Descobrir recursos*.
. Insira as seguintes informações:
+
.. *Tipo de carga de trabalho*: Selecione *Hyper-V*.
.. Se você ainda não armazenou credenciais para este host Hyper-V, selecione *Adicionar credenciais*.
+
... Selecione o agente do Console a ser usado com este host.
... Digite um nome para esta credencial.
... Digite o nome de usuário e a senha da conta.
... Selecione *Concluído*.


.. *Registro de host*: Adicione um novo host Hyper-V inserindo o FQDN ou endereço IP do host, as credenciais, o agente do Console e o número da porta. Se o FQDN não puder ser resolvido pelo agente do Console, use o endereço IP. Para clusters de failover, insira o endereço IP de gerenciamento do cluster.


. Selecione *Descobrir*.
+

TIP: Este processo pode levar alguns minutos.



.Resultado
Depois que o NetApp Backup and Recovery descobre recursos, a página Inventário exibe a carga de trabalho do Hyper-V na lista de cargas de trabalho.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continue para o Painel de NetApp Backup and Recovery

.Passos
. No menu NetApp Console, selecione *Proteção* > *Backup e Recuperação*.
. Selecione o bloco de carga de trabalho do Hyper-V.
. No menu Backup e Recuperação, selecione *Painel*.
. Revise a saúde da proteção de dados.  O número de cargas de trabalho em risco ou protegidas aumenta com base nas cargas de trabalho recém-descobertas, protegidas e armazenadas em backup.

