---
sidebar: sidebar 
permalink: br-start-enable.html 
keywords: backup, Backup and Recovery, enable backup, Console, service, local deployment 
summary: Habilite o backup e a recuperação em um sistema no NetApp Console ou NetApp Console em uma implantação local. 
---
= Ativar o NetApp Backup and Recovery para volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Habilite o NetApp Backup and Recovery para um sistema de storage no NetApp Console ou NetApp Console na implantação local antes de você proteger os volumes ONTAP. Você pode habilitar o serviço ao adicionar um sistema ou posteriormente.



[[enable-backup-and-recovery-in-netapp-console]]
== Ativar backup e recuperação no NetApp Console

Ative o serviço de Backup e Recovery no NetApp Console.

.Passos
. Selecione o menu *Volumes*.
. Na página de visão geral da proteção de volumes, selecione *Configurações de backup*.
. Identifique o sistema que você deseja proteger e selecione *Ativar backup*.
. Selecione *Avançar*.
. Selecione os volumes de origem que deseja proteger e selecione *Avançar*.
. Na página Definir estratégia de backup, selecione a arquitetura de backup e, em seguida, defina as políticas e outros detalhes para snapshots locais, volumes replicados e arquivos de backup. Veja os detalhes das opções de backup dos volumes iniciais que você ativou neste sistema. Depois, selecione *Avançar*.
. Opcionalmente, faça com que o NetApp Backup and Recovery corrija automaticamente as incompatibilidades nos rótulos de backup, Snapshot e replicação.
. Analise as configurações de backup desses volumes e selecione *Ativar backup*.
. Os volumes protegidos aparecem na página de visão geral *Volumes*.




[[enable-backup-and-recovery-in-netapp-console-local-deployment]]
== Habilite o backup e a recuperação na implantação local do NetApp Console

Ative o serviço de Backup e Recovery na implantação local do NetApp Console.

.Antes de começar
Certifique-se de ter obtido uma licença para o NetApp Backup and Recovery. Veja  https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html#obtain-a-license-file["Obtenha uma licença"^] para mais informações.

.Passos
. No menu NetApp Console, selecione *Armazenamento* > *Frotas*.
. Se necessário, adicione sua frota selecionando *Adicionar frota*.
. Selecione *Administração* > *Licenças*.
. Selecione *Adicionar licença* para adicionar uma licença de Backup e Recovery. Para obter mais informações sobre como adicionar uma licença, consulte  https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html#add-a-license["Adicionar uma licença"^].
. Selecione *Storage* > *Fleets* e, em seguida, abra o menu *Systems*.
. Selecione *Adicionar* para adicionar um sistema, insira os detalhes do sistema e salve o novo sistema selecionando *Adicionar*.
. Escolha um sistema e selecione um cluster. No painel de informações à direita, selecione *Ativar* para o serviço de backup e recuperação.
. Selecione *Volumes de backup*.
. Selecione *Avançar*.
. Selecione os volumes de origem que deseja proteger e selecione *Avançar*.
. Na página Definir estratégia de backup, selecione a arquitetura de backup e, em seguida, defina as políticas e outros detalhes para snapshots locais, volumes replicados e arquivos de backup. Veja os detalhes das opções de backup dos volumes iniciais que você ativou neste sistema. Depois, selecione *Avançar*.
. Opcionalmente, faça com que o NetApp Backup and Recovery corrija automaticamente as incompatibilidades nos rótulos de backup, Snapshot e replicação.
. Analise as configurações de backup desses volumes e selecione *Ativar backup*.
. Os volumes protegidos aparecem na página de visão geral *Volumes*.

