---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: No NetApp Backup and Recovery, crie relatórios para visualizar o status dos seus backups, incluindo o número de backups, o número de backups bem-sucedidos e o número de backups com falha.  Você também pode visualizar os detalhes de cada backup, incluindo o tipo de backup, o sistema de armazenamento usado para o backup e a hora do backup. 
---
= Crie relatórios de proteção do Microsoft SQL Server no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crie relatórios para workloads do Microsoft SQL Server no NetApp Backup and Recovery para revisar o status e os detalhes do backup, incluindo contagens de backups bem-sucedidos e com falha, tipos de backup, sistemas de storage e registros de data e hora.



[[create-a-protection-report]]
== Criar um relatório de proteção

*Função obrigatória do NetApp Console* NetApp Backup and Recovery super admin, NetApp Backup and Recovery backup admin, NetApp Backup and Recovery restore admin, NetApp Backup and Recovery clone admin. Se você estiver protegendo dados armazenados em um cluster do Cloud Volumes ONTAP, a função de administrador do Cloud Volumes ONTAP também é necessária. Saiba mais link:reference-roles.html["Funções e privilégios de backup e recuperação"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].

.Passos
. No menu NetApp Backup and Recovery, selecione *Relatórios*.
. Selecione *Criar relatório*.
. Insira os detalhes do escopo do relatório:
+
** *Nome do relatório*: insira um nome exclusivo para o relatório.
** *Tipo de relatório*: Escolha se deseja um relatório por conta ou por carga de trabalho (Microsoft SQL Server).
** *Selecionar host*: Se você selecionou por carga de trabalho, selecione o host para o qual deseja gerar o relatório.
** *Selecionar conteúdo*: Escolha se deseja que o relatório inclua um resumo de todos os backups ou detalhes de cada backup.  (Se você escolheu "Por conta")


. Insira o período do relatório: escolha se você deseja que o relatório inclua dados do último dia, dos últimos 7 dias, dos últimos 30 dias, do último trimestre ou do último ano.
. Insira os detalhes de entrega do relatório: se você quiser que o relatório seja entregue por e-mail, selecione *Enviar relatório por e-mail*. Insira o endereço de e-mail para onde você deseja que o relatório seja enviado.
+
Configure as notificações por e-mail na página Configurações. Para obter detalhes sobre como configurar as notificações por e-mail, consulte link:br-start-configure.html["Configurar definições"].


