---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho KVM com o NetApp Backup and Recovery. 
---
= Restaurar máquinas virtuais KVM com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaure máquinas virtuais KVM a partir de snapshots, de um backup de grupo de proteção replicado para armazenamento secundário ou de backups armazenados em armazenamento de objetos usando o NetApp Backup and Recovery.

.Restaurar a partir desses locais
Você pode restaurar máquinas virtuais de diferentes locais de inicialização:

* Restaurar de um local primário (instantâneo local)
* Restaurar de um recurso replicado no armazenamento secundário
* Restaurar de um backup de armazenamento de objetos


.Restaurar para estes pontos
Você pode restaurar dados para estes pontos:

* Restaurar para o local original
* Restaurar para um local alternativo


.Considerações sobre restauração de armazenamento de objetos
Se você selecionar um arquivo de backup no storage de objetos e a proteção contra ransomware estiver ativa para esse backup (caso tenha habilitado o Datalock e a proteção contra ransomware na política de backup), será solicitado que você execute uma verificação de integridade adicional no arquivo de backup antes de restaurar os dados. Recomendamos que você execute a verificação.


TIP: Você incorrerá em custos extras de saída do seu provedor de nuvem para acessar o conteúdo do arquivo de backup.



== Como funciona a restauração de máquinas virtuais

Ao restaurar máquinas virtuais, ocorre o seguinte:

* Quando você restaura uma carga de trabalho de um arquivo de backup local, o NetApp Backup and Recovery cria um _novo_ recurso usando os dados do backup.
* Ao restaurar a partir de uma VM replicada, você pode restaurá-la para o sistema original ou para um sistema ONTAP local.
* Ao restaurar um backup do armazenamento de objetos, você pode restaurar os dados para o sistema original ou para um sistema ONTAP local.


Na página Restaurar, você pode restaurar uma máquina virtual, mesmo que não se lembre do nome exato, da localização em que ela está ou da data em que estava em bom estado pela última vez. Você pode pesquisar o snapshot usando filtros.



== Restaurar máquinas virtuais KVM

Restaure máquinas virtuais KVM usando o menu Restaurar. Você pode procurar o snapshot pelo nome ou usando filtros.

*Função de console necessária* Superadministrador de backup e recuperação ou função de administrador de restauração de backup e recuperação. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .

.Passos
. No menu do NetApp Console , selecione *Proteção > Backup e recuperação*.
. No menu NetApp Backup and Recovery , selecione *Restaurar*.
. Na lista suspensa à direita do campo de pesquisa de nome, selecione *KVM*.
. Insira o nome da VM que você deseja restaurar ou filtre pelo host da VM ou pool de armazenamento onde o recurso que você deseja restaurar está localizado.
+
Aparece uma lista de instantâneos que correspondem aos seus critérios de pesquisa.

. Selecione o botão *Restaurar* para o instantâneo que você deseja restaurar.
+
Uma lista de possíveis pontos de restauração é exibida.

. Selecione o ponto de restauração que você deseja usar.
. Selecione um local de origem para o instantâneo.
. Selecione *Próximo* para continuar.
. Escolha o destino e as configurações de restauração:
+
[discrete]
===== Seleção de destino

+
[role="tabbed-block"]
====
.Restaurar para o local original
--
.. Selecione o painel *Localização original*.
.. Na seção *Opções pós-restauração*, habilite a opção *Reiniciar máquina virtual* para reiniciar a máquina virtual após a conclusão da operação de restauração.


--
.Restaurar para local alternativo
--
.. Selecione o painel *Localização alternativa*.
.. Na seção *Cloudstack settings*: forneça as seguintes informações:
+
*** *Zona*: Escolha uma zona de destino CloudStack na lista.
*** *Pod*: Escolha um pod de destino dentro da zona selecionada na lista.
*** *Cluster*: escolha um cluster de destino dentro do pod selecionado na lista.
*** *Host*: Escolha um host de destino no cluster a partir da lista.
*** *Pool de storage*: Selecione um pool de storage de destino na lista (o volume de destino deve estar localizado aqui).
*** *Rede*: selecione a rede à qual a VM restaurada será conectada.
*** *Nome da VM*: Insira um nome para a VM a ser restaurada.
*** *Nome de Exibição*: Insira o nome que deve ser exibido para esta VM no Backup and Recovery.
*** *Caminho do pool de storage*: Insira o caminho do pool de storage onde os volumes da máquina virtual serão armazenados.


.. Escolha uma oferta de serviço que defina o seu nível preferido de alocação de recursos na lista *Selecionar oferta de serviço*.
.. Ative a opção *Forçado* para importar a VM restaurada mesmo que um ou mais endereços MAC das NICs da VM já estejam presentes. Se um endereço MAC já existir, um novo endereço MAC será gerado para essa NIC.
.. Na seção *Opções pós-restauração*, considere as seguintes opções:
+
*** *Reiniciar máquina virtual*: Habilite esta opção para inicializar a nova máquina virtual após a restauração.




--
====
. Selecione *Restaurar*.

