---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: O NetApp Backup and Recovery permite que você gerencie ganchos de execução para agir antes ou depois das operações de proteção de aplicativos. 
---
= Gerencie modelos de gancho de execução do Kubernetes em NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Crie modelos de gancho de execução para executar scripts personalizados antes ou depois das operações de proteção para aplicativos Kubernetes gerenciados.

[NOTE]
====
NetApp Backup and Recovery congela e descongela sistemas de arquivos para aplicações como KubeVirt durante a proteção de dados. Você pode desativar esse comportamento globalmente ou para aplicações específicas usando a documentação do Trident Protect:

* Para desabilitar esse comportamento para todos os aplicativos, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Protegendo dados com VMs KubeVirt"] .
* Para desabilitar esse comportamento para um aplicativo específico, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html#define-an-application["Definir uma aplicação"] .


====
.Função necessária do NetApp Console
Administrador da organização ou administrador do SnapCenter . link:reference-roles.html["Saiba mais sobre as funções de acesso do NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .



[[types-of-execution-hooks]]
== Tipos de ganchos de execução

O NetApp Backup and Recovery suporta os seguintes tipos de ganchos de execução com base em quando são executados:

* Pré-instantâneo
* Pós-instantâneo
* Pré-backup
* Pós-backup
* Pós-restauração




[[order-of-execution]]
=== Ordem de execução

Quando uma operação de proteção de dados é executada, os eventos de gancho de execução ocorrem na seguinte ordem:

. Todos os ganchos de execução de pré-operação personalizados aplicáveis são executados nos contêineres apropriados. Você pode criar vários ganchos de pré-operação personalizados, mas sua ordem de execução não é garantida nem configurável.
. Congelamentos do sistema de arquivos ocorrem, se aplicável.
. A operação de proteção de dados é realizada.
. Sistemas de arquivos congelados são descongelados, se aplicável.
. O NetApp Backup and Recovery executa quaisquer hooks de pós-operação personalizados aplicáveis nos contêineres apropriados. Você pode criar vários hooks de pós-operação personalizados, mas a ordem de execução deles não é garantida nem configurável.


Se você criar vários hooks do mesmo tipo, a ordem de execução deles não é garantida. Hooks de tipos diferentes sempre são executados na ordem especificada. Por exemplo, os hooks são executados nesta ordem quando uma configuração inclui todos os tipos de hook suportados:

. Ganchos pré-snapshot são executados
. Ganchos pós-snapshot são executados
. Os ganchos de pré-backup são executados
. Os hooks pós-backup são executados



NOTE: Teste os scripts de execução antes de habilitá-los na produção.  Use 'kubectl exec' para testar scripts e, em seguida, verifique snapshots e backups clonando o aplicativo em um namespace temporário e restaurando-o.


NOTE: Se um gancho de execução pré-snapshot adicionar, alterar ou remover recursos do Kubernetes, essas alterações serão incluídas no snapshot ou backup e em qualquer operação de restauração subsequente.



[[important-notes-about-custom-execution-hooks]]
== Notas importantes sobre ganchos de execução personalizados

Considere o seguinte ao planejar os hooks de execução para seus aplicativos.

* Um gancho de execução deve usar um script para executar ações.  Muitos ganchos de execução podem referenciar o mesmo script.
* Os ganchos de execução devem ser scripts shell executáveis.
* O tamanho do script é limitado a 96 KB.
* As configurações do gancho de execução e quaisquer critérios correspondentes são usados para determinar quais ganchos são aplicáveis a uma operação de snapshot, backup ou restauração.



NOTE: Os hooks de execução podem reduzir ou desativar a funcionalidade do aplicativo. Faça com que seus hooks personalizados sejam executados o mais rápido possível. Se você cancelar uma operação de backup ou de snapshot que tenha hooks de execução associados, esses hooks ainda serão executados se a operação já tiver sido iniciada. A lógica de um hook de execução pós-backup não pode pressupor que o backup foi concluído.



[[execution-hook-filters]]
== Filtros de gancho de execução

Ao adicionar ou editar um gancho de execução para um aplicativo, você pode adicionar filtros a esse gancho para controlar a quais contêineres ele corresponde. Os filtros são úteis para aplicativos que usam a mesma imagem de contêiner em todos os contêineres, mas que podem usar cada imagem para uma finalidade diferente (como Elasticsearch). Os filtros permitem criar cenários em que os ganchos de execução são executados em alguns, mas não necessariamente em todos os contêineres idênticos. Se você criar vários filtros para um único gancho de execução, eles serão combinados com um operador lógico AND. Você pode ter até 10 filtros ativos por gancho de execução.

Cada filtro que você adiciona a um gancho de execução usa uma expressão regular para corresponder contêineres no seu cluster. Quando um gancho corresponde a um contêiner, o gancho executa o script associado nesse contêiner. As expressões regulares para filtros usam a sintaxe Regular Expression 2 (RE2), que não permite criar um filtro que exclua contêineres da lista de correspondências. Para obter informações sobre a sintaxe que o NetApp Backup and Recovery oferece suporte para expressões regulares em filtros de ganchos de execução, consulte  https://github.com/google/re2/wiki/Syntax["Suporte à sintaxe de Expressão Regular 2 (RE2)"^].


NOTE: Se você adicionar um filtro de namespace a um gancho de execução executado após uma operação de restauração ou clonagem e a origem e o destino da restauração ou clonagem estiverem em namespaces diferentes, o filtro de namespace será aplicado somente ao namespace de destino.



[[execution-hook-examples]]
== Exemplos de ganchos de execução

Visite o https://github.com/NetApp/Verda["Projeto NetApp Verda GitHub"] para baixar ganchos de execução reais para aplicativos populares, como Apache Cassandra e Elasticsearch.  Você também pode ver exemplos e obter ideias para estruturar seus próprios ganchos de execução personalizados.


NOTE: Os scripts no repositório GitHub Verda são fornecidos como estão e não são oficialmente suportados pela NetApp. Somente a estrutura de execução de hooks dentro do Trident Protect e do Backup and Recovery é oficialmente suportada pela NetApp.



[[create-an-execution-hook-template]]
== Crie um modelo de gancho de execução

Você pode criar um modelo de gancho de execução personalizado que pode ser usado para executar ações antes ou depois de uma operação de proteção de dados em um aplicativo.


NOTE: Os modelos que você cria aqui só podem ser usados ao proteger cargas de trabalho do Kubernetes.

.Passos
. No Console, vá para *Proteção* > *Backup e recuperação*.
. Selecione a aba *Configurações*.
. Expanda a seção *Modelo de gancho de execução*.
. Selecione *Criar modelo de gancho de execução*.
. Digite um nome para o gancho de execução.
. Opcionalmente, escolha um tipo de gancho. Por exemplo, um gancho pós-restauração é executado após a conclusão da operação de restauração.
. Na caixa de texto *Script*, insira o script de shell executável que você deseja executar como parte do modelo de gancho de execução.  Opcionalmente, você pode selecionar *Carregar script* para carregar um arquivo de script.
. Selecione *Criar*.
+
Depois de criar o modelo, ele aparece na lista de modelos na seção *Modelo de gancho de execução*.


