---
sidebar: sidebar 
permalink: br-use-manage-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Você pode fazer backup de dados de aplicativos do Microsoft SQL Server de sistemas ONTAP locais para Amazon Web Services, Microsoft Azure, Google Cloud Platform e StorageGRID, garantindo que seus dados estejam protegidos. Os backups são gerados automaticamente e armazenados em um armazenamento de objetos na sua conta de nuvem pública ou privada.  Você pode implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem. 
---
= Visão geral do gerenciamento de recursos com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gerenciar recursos no NetApp Backup and Recovery é essencial para garantir que seus dados estejam protegidos.  Você pode gerenciar recursos como backups, bancos de dados, instâncias, hosts de aplicativos e ambientes de trabalho.  Você pode visualizar, editar e excluir configurações de proteção dos seus recursos.

Você pode realizar as seguintes tarefas relacionadas ao gerenciamento de seus recursos:

* link:br-use-manage-inventory.html["Gerenciar inventário"] .
* link:br-use-manage-snapshots.html["Gerenciar instantâneos"] .
* link:br-use-manage-kubernetes-clusters.html["Gerenciar clusters do Kubernetes"] .
* link:br-use-manage-kubernetes-applications.html["Gerenciar aplicativos Kubernetes"] .

