---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: O NetApp Backup and Recovery permite que você gerencie ganchos de execução para agir antes ou depois das operações de proteção de aplicativos. 
---
= Gerenciar modelos de ganchos de execução de NetApp Backup and Recovery para cargas de trabalho do Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um gancho de execução é uma ação personalizada que você pode configurar para ser executada em conjunto com uma operação de proteção de dados de um aplicativo Kubernetes gerenciado.  Por exemplo, se você tiver um aplicativo de banco de dados, poderá usar um gancho de execução para pausar todas as transações do banco de dados antes de um instantâneo e retomar as transações após a conclusão do instantâneo.  Isso garante instantâneos consistentes com o aplicativo.  Ao criar um modelo de gancho de execução, você pode especificar o tipo de gancho, o script a ser executado e quaisquer filtros que determinem a quais contêineres o gancho se aplica.  Você pode então usar o modelo para associar ganchos de execução aos seus aplicativos.

[NOTE]
====
Por padrão, o NetApp Backup and Recovery congela e descongela automaticamente os sistemas de arquivos de determinados aplicativos, como o KubeVirt, durante operações de proteção de dados. Opcionalmente, você pode desabilitar esse comportamento globalmente ou para aplicativos específicos usando instruções da documentação do Trident Protect:

* Para desabilitar esse comportamento para todos os aplicativos, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Protegendo dados com VMs KubeVirt"] .
* Para desabilitar esse comportamento para um aplicativo específico, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html#define-an-application["Definir uma aplicação"] .


====
.Função necessária do NetApp Console
Administrador da organização ou administrador do SnapCenter . link:reference-roles.html["Saiba mais sobre as funções de acesso do NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .



== Tipos de ganchos de execução

O NetApp Backup and Recovery oferece suporte aos seguintes tipos de ganchos de execução, com base em quando eles podem ser executados:

* Pré-instantâneo
* Pós-instantâneo
* Pré-backup
* Pós-backup
* Pós-restauração




=== Ordem de execução

Quando uma operação de proteção de dados é executada, os eventos de gancho de execução ocorrem na seguinte ordem:

. Todos os ganchos de execução de pré-operação personalizados aplicáveis são executados nos contêineres apropriados.  Você pode criar e executar quantos ganchos de pré-operação personalizados precisar, mas a ordem de execução desses ganchos antes da operação não é garantida nem configurável.
. Congelamentos do sistema de arquivos ocorrem, se aplicável.
. A operação de proteção de dados é realizada.
. Sistemas de arquivos congelados são descongelados, se aplicável.
. Todos os ganchos de execução pós-operação personalizados aplicáveis são executados nos contêineres apropriados.  Você pode criar e executar quantos ganchos pós-operação personalizados precisar, mas a ordem de execução desses ganchos após a operação não é garantida nem configurável.


Se você criar vários ganchos de execução do mesmo tipo (por exemplo, pré-instantâneo), a ordem de execução desses ganchos não será garantida.  Entretanto, a ordem de execução de ganchos de diferentes tipos é garantida.  Por exemplo, a seguir está a ordem de execução de uma configuração que possui todos os diferentes tipos de ganchos:

. Ganchos pré-instantâneos executados
. Ganchos pós-instantâneos executados
. Ganchos de pré-backup executados
. Ganchos pós-backup executados



NOTE: Você deve sempre testar seus scripts de gancho de execução antes de habilitá-los em um ambiente de produção.  Você pode usar o comando 'kubectl exec' para testar os scripts convenientemente.  Depois de habilitar os ganchos de execução em um ambiente de produção, teste os snapshots e backups resultantes para garantir que sejam consistentes.  Você pode fazer isso clonando o aplicativo em um namespace temporário, restaurando o snapshot ou backup e, em seguida, testando o aplicativo.


NOTE: Se um gancho de execução pré-snapshot adicionar, alterar ou remover recursos do Kubernetes, essas alterações serão incluídas no snapshot ou backup e em qualquer operação de restauração subsequente.



== Notas importantes sobre ganchos de execução personalizados

Considere o seguinte ao planejar ganchos de execução para seus aplicativos.

* Um gancho de execução deve usar um script para executar ações.  Muitos ganchos de execução podem referenciar o mesmo script.
* Os ganchos de execução precisam ser escritos no formato de scripts de shell executáveis.
* O tamanho do script é limitado a 96 KB.
* As configurações do gancho de execução e quaisquer critérios correspondentes são usados para determinar quais ganchos são aplicáveis a uma operação de snapshot, backup ou restauração.



NOTE: Como os ganchos de execução geralmente reduzem ou desabilitam completamente a funcionalidade do aplicativo em que estão sendo executados, você deve sempre tentar minimizar o tempo que seus ganchos de execução personalizados levam para serem executados.  Se você iniciar uma operação de backup ou snapshot com ganchos de execução associados, mas depois cancelá-la, os ganchos ainda poderão ser executados se a operação de backup ou snapshot já tiver começado.  Isso significa que a lógica usada em um gancho de execução pós-backup não pode assumir que o backup foi concluído.



== Filtros de gancho de execução

Ao adicionar ou editar um gancho de execução para um aplicativo, você pode adicionar filtros ao gancho de execução para gerenciar quais contêineres o gancho corresponderá.  Os filtros são úteis para aplicativos que usam a mesma imagem de contêiner em todos os contêineres, mas podem usar cada imagem para uma finalidade diferente (como o Elasticsearch).  Os filtros permitem que você crie cenários em que os ganchos de execução são executados em alguns contêineres idênticos, mas não necessariamente em todos.  Se você criar vários filtros para um único gancho de execução, eles serão combinados com um operador lógico AND.  Você pode ter até 10 filtros ativos por gancho de execução.

Cada filtro que você adiciona a um gancho de execução usa uma expressão regular para corresponder aos contêineres no seu cluster.  Quando um gancho corresponde a um contêiner, o gancho executará seu script associado naquele contêiner.  Expressões regulares para filtros usam a sintaxe Regular Expression 2 (RE2), que não oferece suporte à criação de um filtro que exclua contêineres da lista de correspondências.  Para obter informações sobre a sintaxe que o NetApp Backup and Recovery oferece suporte para expressões regulares em filtros de gancho de execução, consulte https://github.com/google/re2/wiki/Syntax["Suporte à sintaxe de Expressão Regular 2 (RE2)"^] .


NOTE: Se você adicionar um filtro de namespace a um gancho de execução executado após uma operação de restauração ou clonagem e a origem e o destino da restauração ou clonagem estiverem em namespaces diferentes, o filtro de namespace será aplicado somente ao namespace de destino.



== Exemplos de ganchos de execução

Visite o https://github.com/NetApp/Verda["Projeto NetApp Verda GitHub"] para baixar ganchos de execução reais para aplicativos populares, como Apache Cassandra e Elasticsearch.  Você também pode ver exemplos e obter ideias para estruturar seus próprios ganchos de execução personalizados.



== Crie um modelo de gancho de execução

Você pode criar um modelo de gancho de execução personalizado que pode ser usado para executar ações antes ou depois de uma operação de proteção de dados em um aplicativo.

.Passos
. No Console, vá para *Proteção* > *Backup e recuperação*.
. Selecione a aba *Configurações*.
. Expanda a seção *Modelo de gancho de execução*.
. Selecione *Criar modelo de gancho de execução*.
. Digite um nome para o gancho de execução.
. Opcionalmente, escolha um tipo de gancho. Por exemplo, um gancho pós-restauração é executado após a conclusão da operação de restauração.
. Na caixa de texto *Script*, insira o script de shell executável que você deseja executar como parte do modelo de gancho de execução.  Opcionalmente, você pode selecionar *Carregar script* para carregar um arquivo de script.
. Selecione *Criar*.
+
O modelo é criado e aparece na lista de modelos na seção *Modelo de gancho de execução*.


