---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: Proteja os dados do seu aplicativo Microsoft SQL Server de sistemas ONTAP locais para Amazon Web Services, Microsoft Azure ou StorageGRID usando o NetApp Backup and Recovery. 
---
= Proteja as cargas de trabalho do Microsoft SQL Server com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Faça backup dos bancos de dados do Microsoft SQL Server de sistemas ONTAP locais para AWS, Azure ou StorageGRID usando o NetApp Backup and Recovery. Implemente uma estratégia de backup 3-2-1 com Snapshots no storage primário, replicação para storage secundário e cópias para storage de objetos.

O NetApp Backup and Recovery utiliza o NetApp SnapMirror para sincronizar backups, criando snapshots e transferindo-os para os locais de backup.

Utilize os seguintes fluxos de trabalho para proteger seus dados:

* link:concept-start-prereq-snapcenter-import.html["Configurar itens adicionais se importar do SnapCenter"]
* link:br-start-discover.html["Descubra cargas de trabalho do Microsoft SQL Server e, opcionalmente, importe recursos do SnapCenter"]
* link:br-use-mssql-backup.html["Faça backup de cargas de trabalho com snapshots locais no armazenamento primário ONTAP local"]
* link:br-use-mssql-backup.html["Replique cargas de trabalho para armazenamento secundário ONTAP"]
* link:br-use-mssql-backup.html["Fazer backup de cargas de trabalho em um local de armazenamento de objetos"]
* link:br-use-mssql-backup.html["Faça backup das cargas de trabalho agora"]
* link:br-use-mssql-restore.html["Restaurar cargas de trabalho"]
* link:br-use-mssql-clone.html["Clonar cargas de trabalho"]
* link:br-use-manage-inventory.html["Gerenciar inventário de cargas de trabalho"]
* link:br-use-manage-snapshots.html["Gerenciar instantâneos"]


Para fazer backup de cargas de trabalho, crie políticas que gerenciam operações de backup e restauração. Verlink:br-use-policies-create.html["Criar políticas"] para mais informações.

.Destinos de backup suportados
O NetApp Backup and Recovery oferece suporte a backups de instâncias e bancos de dados do Microsoft SQL Server dos seguintes sistemas de origem para os sistemas secundários e armazenamentos de objetos listados em nuvens públicas e privadas. Os Snapshots permanecem no sistema de origem.

[cols="33,33,33"]
|===
| Sistema de origem | Sistema secundário (replicação) | Armazenamento de objetos (backup) 


| Cloud Volumes ONTAP na AWS | Cloud Volumes ONTAP no sistema ONTAP local da AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP no Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure | Azure Blob ONTAP S3 


| Sistema ONTAP local | Sistema Cloud Volumes ONTAP ONTAP | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / D 
|===
.Destinos de restauração suportados
Você pode restaurar instâncias e bancos de dados do Microsoft SQL Server a partir de um backup que reside no storage primário, em um sistema secundário (volume replicado) ou storage de objetos (arquivo de backup) para os seguintes sistemas de destino. Os Snapshots residem no sistema de origem e só podem ser restaurados para esse mesmo sistema.

[cols="33,33,33"]
|===
2+| Do local do arquivo de backup | Para o sistema de destino 


| *armazenamento de objetos (backup)* | *Sistema secundário (replicação)* |  


| Amazon S3 | Cloud Volumes ONTAP no sistema ONTAP local da AWS | Cloud Volumes ONTAP na AWS no sistema ONTAP local ONTAP S3 


| Blob do Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure | Cloud Volumes ONTAP no Azure Sistema ONTAP local ONTAP S3 


| StorageGRID | Sistema Cloud Volumes ONTAP ONTAP | Sistema ONTAP local ONTAP S3 
|===

NOTE: Referências a "sistemas ONTAP locais" incluem sistemas FAS e AFF .
