---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho do Oracle Database com NetApp Backup and Recovery. 
---
= Restaure cargas de trabalho do Oracle Database com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaure cargas de trabalho do Oracle Database a partir de snapshots, backups replicados em storage secundário ou backups armazenados em storage de objetos usando o NetApp Backup and Recovery.

.Restaurar a partir desses locais
Você pode restaurar bancos de dados de diferentes locais de partida:

* Restaurar de um local primário (instantâneo local)
* Restaurar de um recurso replicado no armazenamento secundário
* Restaurar de um backup de armazenamento de objetos


.Restaurar para estes pontos
Você pode restaurar dados para o local original; restaurar para um local alternativo não está disponível nesta versão de visualização privada.

* Restaurar para o local original




[[how-oracle-database-restore-works]]
== Como funciona a restauração do banco de dados Oracle

Ao restaurar cargas de trabalho do Oracle Database, ocorre o seguinte:

* Quando você restaura um banco de dados de um snapshot local, o NetApp Backup and Recovery cria um _novo_ recurso usando os dados do backup.
* Ao restaurar a partir do armazenamento replicado, você pode restaurá-lo para o local original.
* Ao restaurar um backup do armazenamento de objetos, você pode restaurar os dados para o armazenamento de origem ou para um sistema ONTAP local e recuperar o banco de dados de lá.


Na página Restaurar (também conhecida como Pesquisar e Restaurar), você pode restaurar um banco de dados, mesmo que não se lembre do nome exato, do local em que ele reside ou da data em que esteve em boas condições pela última vez.  Você pode pesquisar no banco de dados usando filtros.



[[restore-an-oracle-database]]
== Restaurar um banco de dados Oracle

Dependendo das suas necessidades, restaure um banco de dados Oracle para um ponto específico no tempo, para um número de alteração do sistema (SCN) específico ou para o último estado íntegro. Você também pode restaurar o banco de dados a partir de Snapshots e ignorar o processo de recuperação automatizada, por exemplo, se você quiser realizar a recuperação manualmente. Você pode pesquisar o banco de dados usando seu nome ou com filtros específicos.

*Função necessária do NetApp Console*: superadministrador de backup e recuperação ou administrador de restauração de backup e recuperação https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].

.Passos
. No menu do NetApp Console , selecione *Proteção > Backup e recuperação*.
. No menu NetApp Backup and Recovery , selecione *Restaurar*.
. Na lista suspensa à direita do campo de pesquisa de nome, selecione *Oracle*.
. Digite o nome do banco de dados que você deseja restaurar ou filtre pelo host do banco de dados onde o banco de dados que você deseja restaurar está localizado.
+
Aparece uma lista de instantâneos que correspondem aos seus critérios de pesquisa.

. Selecione o botão *Restaurar* para o banco de dados que você deseja restaurar.
. Escolha uma opção de restauração:
+
[role="tabbed-block"]
====
.Restaurar para um ponto específico no tempo
--
.. Selecione *Restaurar para um ponto específico no tempo*.
.. Selecione *Avançar*.
.. Escolha uma data no menu suspenso e selecione *Pesquisar*.
+
Uma lista de instantâneos correspondentes na data especificada é exibida.



--
.Restaurar para um número de alteração do sistema (SCN) específico
--
.. Selecione *Restaurar para um número de alteração do sistema (SCN) específico*.
.. Selecione *Avançar*.
.. Digite o SCN a ser usado como ponto de restauração e selecione *Pesquisar*.
+
Uma lista de instantâneos correspondentes para o SCN especificado é exibida.



--
.Restaurar para o backup mais recente (último estado bom)
--
.. Selecione *Restaurar para o backup mais recente*.
.. Selecione *Avançar*.
+
Os backups completos e de log mais recentes são exibidos.



--
.Restaurar de instantâneos sem recuperação
--
.. Selecione *Restaurar de instantâneos sem recuperação*.
.. Selecione *Avançar*.
+
Os instantâneos correspondentes são exibidos.



--
====
. Selecione um local de origem para o instantâneo.
. Selecione *Próximo* para continuar.
. Escolha o destino e as configurações de restauração:


[discrete]
===== Seleção de destino

[role="tabbed-block"]
====
.Restaurar para o local original
--
[NOTE]
====
Se você estiver restaurando PDBs ou espaços de tabela PDB para um ponto específico no tempo ou SCN:

* Selecione apenas um PDB. A recuperação de ponto no tempo não é compatível com a restauração de vários PDBs.
* O PDB $SEEDnão pode ser selecionado para recuperação de ponto no tempo.
* A restauração do arquivo de controle não pode ser combinada com a recuperação de ponto no tempo de PDBs ou tablespaces.
* Certifique-se de que o backup de dados e os backups de log necessários estejam catalogados.


====
. *Configurações de destino*:
. Selecione o que você deseja restaurar:
+
** Selecione *Todos os arquivos de dados* para restaurar todo o banco de dados ou o banco de dados contêiner (CDB).
** Selecione *Bancos de dados plugáveis (PDBs)* para restaurar um ou mais PDBs de um CDB sem afetar os outros PDBs no contêiner. Em seguida, selecione os PDBs na lista.
** Selecione *Tablespaces de banco de dados plugável (PDB)* (exibidos como *Tablespaces* para um banco de dados não-CDB) para restaurar tablespaces PDB específicos. Em seguida, selecione o PDB e os tablespaces.


. Opcionalmente, habilite a opção *Arquivos de controle* para restaurar também os arquivos de controle do banco de dados. Essa opção não está disponível para recuperação de ponto no tempo ou SCN de PDBs ou tablespaces de PDBs.
. Opcionalmente, habilite a opção *Alterar o estado do banco de dados, se necessário, para restauração e recuperação* para permitir que o NetApp Backup and Recovery gerencie o estado do banco de dados dependendo do tipo de recuperação.
. Opcionalmente, habilite a opção *Forçar restauração no local* para usar um método de restauração mais rápido para bancos de dados SAN/ASM, ignorando a verificação de validação de arquivos externos. O banco de dados e o grupo de discos ASM são restaurados ao ponto de criação do backup.
. Especifique o local dos arquivos de log de arquivamento externo se estiver restaurando PDBs ou tablespaces de PDB para um ponto específico no tempo ou SCN. Insira o local onde o RMAN cria a instância auxiliar para realizar a recuperação. Insira um caminho do sistema de arquivos que comece com "/" ou um grupo de discos ASM que comece com "+". Use os botões "mais" e "menos" ao lado do campo de entrada de texto para adicionar ou remover locais.
. Opcionalmente, habilite a opção *Abrir o banco de dados ou o banco de dados contêiner no modo LEITURA/GRAVAÇÃO após a recuperação* para abrir os bancos de dados no modo LEITURA/GRAVAÇÃO após restaurá-los. Isso coloca os tablespaces restaurados online.
. *Prescripts e postscripts*:
+
** *Prescript*: Opcionalmente, habilite esta opção e insira o caminho completo para um script que deve ser executado antes da operação de restauração e quaisquer argumentos que o script receba.
** *Postscript*: Opcionalmente, habilite esta opção e insira o caminho completo para um script que deve ser executado após a operação de restauração e quaisquer argumentos que o script aceite.


. Escolha um valor de tempo limite para o script. Se o script não for executado dentro desse período, a restauração prosseguirá mesmo assim.
. Selecione *Restaurar*.


--
.Restaurar para local alternativo
--
Não disponível para cargas de trabalho do Oracle Database nesta versão prévia.

--
====