---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Você pode fazer backup de dados de aplicativos do Microsoft SQL Server de sistemas ONTAP locais para Amazon Web Services, Microsoft Azure e StorageGRID, garantindo que seus dados estejam protegidos. Os backups são gerados automaticamente e armazenados em um armazenamento de objetos na sua conta de nuvem pública ou privada.  Você pode implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem. 
---
= Visão geral da proteção de cargas de trabalho do Microsoft SQL com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja os dados dos seus aplicativos Microsoft SQL Server de sistemas ONTAP locais para Amazon Web Services, Microsoft Azure ou StorageGRID usando o NetApp Backup and Recovery. Os backups são gerados automaticamente e armazenados em um repositório de objetos na sua conta de nuvem pública ou privada com base nas políticas que você cria.  Você pode implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem.

Os benefícios da abordagem 3-2-1 incluem:

* Várias cópias de dados fornecem proteção multicamadas contra ameaças de segurança cibernética internas e externas.
* Vários tipos de mídia garantem a viabilidade de failover no caso de falha física ou lógica de um tipo de mídia.
* A cópia no local facilita restaurações rápidas, com cópias externas disponíveis caso a cópia no local seja comprometida.


O NetApp Backup and Recovery utiliza a tecnologia de replicação de dados NetApp SnapMirror para garantir que todos os backups sejam totalmente sincronizados, criando cópias instantâneas e transferindo-as para os locais de backup.

Você pode atingir as seguintes metas de proteção:

* link:concept-start-prereq-snapcenter-import.html["Configurar itens adicionais se importar do SnapCenter"]
* link:br-start-discover.html["Descubra cargas de trabalho do Microsoft SQL Server e, opcionalmente, importe recursos do SnapCenter"]
* link:br-use-mssql-backup.html["Faça backup de cargas de trabalho com snapshots locais no armazenamento primário ONTAP local"]
* link:br-use-mssql-backup.html["Replique cargas de trabalho para armazenamento secundário ONTAP"]
* link:br-use-mssql-backup.html["Fazer backup de cargas de trabalho em um local de armazenamento de objetos"]
* link:br-use-mssql-backup.html["Faça backup das cargas de trabalho agora"]
* link:br-use-mssql-restore-overview.html["Restaurar cargas de trabalho"]
* link:br-use-mssql-clone.html["Clonar cargas de trabalho"]
* link:br-use-manage-inventory.html["Gerenciar inventário de cargas de trabalho"]
* link:br-use-manage-snapshots.html["Gerenciar instantâneos"]


Para fazer backup de cargas de trabalho, normalmente você cria políticas que controlam as operações de backup e restauração.  Verlink:br-use-policies-create.html["Criar políticas"] para mais informações.

.Destinos de backup suportados
O NetApp Backup and Recovery permite que você faça backup de instâncias e bancos de dados do Microsoft SQL Server dos seguintes sistemas de origem para os seguintes sistemas secundários e armazenamento de objetos em provedores de nuvem pública e privada.  Cópias de instantâneos residem no sistema de origem.

[cols="33,33,33"]
|===
| Sistema de origem | Sistema secundário (Replicação) | Armazenamento de Objetos de Destino (Backup) 


| Cloud Volumes ONTAP na AWS | Cloud Volumes ONTAP no sistema ONTAP local da AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP no Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure | Azure Blob ONTAP S3 


| Sistema ONTAP local | Sistema Cloud Volumes ONTAP ONTAP | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | NA ifdef::gcp[] fim se::gcp[] ifdef::gcp[] fim se::gcp[] 
|===
.Destinos de restauração suportados
Você pode restaurar instâncias e bancos de dados do Microsoft SQL Server de um backup que reside no armazenamento primário ou em um sistema secundário (um volume replicado) ou no armazenamento de objetos (um arquivo de backup) para os seguintes sistemas.  Cópias de instantâneos residem no sistema de origem e podem ser restauradas somente no mesmo sistema.

[cols="33,33,33"]
|===
2+| Do local do arquivo de backup | Para o sistema de destino 


| *Armazenamento de Objetos (Backup)* | *Sistema Secundário (Replicação)* |  


| Amazon S3 | Cloud Volumes ONTAP no sistema ONTAP local da AWS | Volumes de nuvem no sistema ONTAP local da AWS ONTAP S3 


| Blob do Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure ONTAP S3 ifdef::gcp[] endif::gcp[] 


| StorageGRID | Sistema Cloud Volumes ONTAP ONTAP | Sistema ONTAP local ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / D 
|===

NOTE: Referências a "sistemas ONTAP locais" incluem sistemas FAS e AFF .
