---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: O NetApp Backup and Recovery permite restaurar aplicativos que você protegeu com uma política de proteção. 
---
= Restaurar aplicações Kubernetes usando a interface web
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Backup and Recovery permite restaurar aplicativos que você protegeu com uma política de proteção. Para restaurar um aplicativo, ele precisa ter pelo menos um ponto de restauração disponível. Um ponto de restauração consiste no snapshot local ou no backup no repositório de objetos (ou ambos). Você pode restaurar um aplicativo usando o arquivo local, secundário ou do repositório de objetos.

.Antes de começar
Se você estiver restaurando um aplicativo que foi copiado usando Trident Protect, certifique-se de que Trident Protect esteja instalado tanto no cluster de origem quanto no cluster de destino.

.Função necessária do NetApp Console
Administrador da organização ou administrador do SnapCenter . link:reference-roles.html["Saiba mais sobre as funções de acesso do NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .

.Passos
. No menu NetApp Backup e Recuperação, selecione *Restaurar*.
. Escolha um aplicativo Kubernetes da lista e selecione *Visualizar e restaurar* para esse aplicativo.
+
A lista de pontos de restauração é exibida.

. Selecione o botão *Restaurar* para o ponto de recuperação que deseja usar.


[discrete]
===== Configurações gerais

. Escolha o local de origem do qual restaurar.
. Escolha o cluster de destino na lista *Cluster*.
+

NOTE: Restaurar um snapshot local criado pelo Trident Protect para um cluster diferente não é suportado no momento.

. Escolha restaurar nos namespaces originais ou em novos namespaces.
. Se você optar por restaurar para novos namespaces, insira o namespace ou namespaces de destino a serem usados.
. Selecione *Avançar*.


[discrete]
===== Seleção de recursos

. Escolha se deseja restaurar todos os recursos associados ao aplicativo ou usar um filtro para selecionar recursos específicos para restaurar:


[role="tabbed-block"]
====
.Restaurar todos os recursos
--
. Selecione *Restaurar todos os recursos*.
. Selecione *Avançar*.


--
.Restaurar recursos específicos
--
. Selecione *Recursos seletivos*.
. Escolha o comportamento do filtro de recursos.  Se você escolher *Incluir*, os recursos selecionados serão restaurados.  Se você escolher *Excluir*, os recursos selecionados não serão restaurados.
. Selecione *Adicionar regras* para adicionar regras que definem filtros para selecionar recursos.  Você precisa de pelo menos uma regra para filtrar recursos.
+
Cada regra pode filtrar critérios como namespace do recurso, rótulos, grupo, versão e tipo.

. Selecione *Salvar* para salvar cada regra.
. Depois de adicionar todas as regras necessárias, selecione *Pesquisar* para ver os recursos disponíveis no arquivo de backup que correspondem aos seus critérios de filtro.
+

NOTE: Os recursos mostrados são os recursos que existem atualmente no cluster.

. Quando estiver satisfeito com os resultados, selecione *Avançar*.


--
====
[discrete]
===== Configurações de destino

. Expanda a seção *Configurações de destino* e escolha restaurar para a classe de armazenamento padrão, para uma classe de armazenamento diferente ou, se estiver restaurando para um cluster diferente, mapear as classes de armazenamento para o cluster de destino.
. Se você optar por restaurar para uma classe de armazenamento diferente, selecione uma classe de armazenamento de destino que corresponda a cada classe de armazenamento de origem.
. Opcionalmente, se estiver restaurando um backup ou snapshot criado com Trident Protect, visualize os detalhes do AppVault usado como o bucket de armazenamento para a operação de restauração. Se houver uma alteração no seu ambiente ou no status do AppVault, selecione *Sincronizar App Vault* para atualizar os detalhes.
+

NOTE: Se você precisar criar um AppVault em um cluster Kubernetes para facilitar a restauração de um backup ou snapshot criado usando Trident Protect, consulte  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-appvault-custom-resources.html["Use objetos do Trident Protect AppVault para gerenciar buckets"].

. Opcionalmente, expanda a seção *Scripts de restauração* e habilite a opção *Pós-script* para escolher um modelo de gancho de execução que será executado após a conclusão da operação de restauração. Se necessário, insira quaisquer argumentos que o script precise e adicione seletores de rótulo para filtrar recursos com base nos rótulos dos recursos.
. Selecione *Restaurar*.

