---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Você pode proteger máquinas virtuais Oracle de sistemas ONTAP locais até Amazon Web Services, Microsoft Azure, Google Cloud Platform e StorageGRID, garantindo que seus dados estejam protegidos. 
---
= Visão geral da proteção de cargas de trabalho do Oracle Database
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja bancos de dados e logs do Oracle usando NetApp Backup and Recovery. Obtenha backups e restaurações rápidos, com uso eficiente de espaço, consistentes com falhas e consistentes com o banco de dados. Faça backup de cargas de trabalho do Oracle Database no AWS S3, NetApp StorageGRID, Azure Blob Storage ou ONTAP S3. Restaure backups em um host Oracle local.

Use o NetApp Backup and Recovery para implementar uma estratégia de proteção 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem. Os benefícios da abordagem 3-2-1 incluem:

* Várias cópias de dados protegem contra ameaças internas e externas à segurança cibernética.
* Usar diferentes tipos de mídia ajuda na recuperação caso um tipo falhe.
* Você pode restaurar rapidamente a partir da cópia local e usar as cópias externas se a cópia local estiver comprometida.



NOTE: Para alternar entre as versões da interface de usuário do NetApp Backup and Recovery , consultelink:br-start-switch-ui.html["Mudar para a interface de usuário anterior do NetApp Backup and Recovery"] .

Você pode usar NetApp Backup and Recovery para executar as seguintes tarefas relacionadas às cargas de trabalho do Oracle Database:

* link:br-start-discover-oracle.html["Descubra cargas de trabalho do Oracle Database"]
* link:br-use-oracle-protection-groups.html["Criar e gerenciar grupos de proteção para cargas de trabalho do Oracle Database"]
* link:br-use-oracle-backup.html["Fazer backup das cargas de trabalho do Oracle Database"]
* link:br-use-oracle-restore.html["Restaurar cargas de trabalho do Oracle Database"]

