---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com NetApp Backup and Recovery. 
---
= Visão geral da proteção de cargas de trabalho do VMware com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja suas VMs e datastores do VMware com NetApp Backup and Recovery. NetApp Backup and Recovery oferece operações de backup e restauração rápidas, com uso eficiente de espaço, consistentes com falhas e consistentes com a VM. Você pode fazer backup de cargas de trabalho do VMware em destinos de backup compatíveis e restaurar cargas de trabalho do VMware de volta para um host VMware local.


NOTE: Esta versão do NetApp Backup and Recovery oferece suporte apenas ao VMware vCenter e não descobre vVols ou VMs em vVols.

Use o NetApp Backup and Recovery para implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem. Os benefícios da abordagem 3-2-1 incluem:

* Várias cópias de dados protegem contra ameaças internas e externas à segurança cibernética.
* Usar diferentes tipos de mídia ajuda na recuperação caso um tipo falhe.
* Você pode restaurar rapidamente a partir da cópia local e usar as cópias externas se a cópia local estiver comprometida.


Você pode usar o NetApp Backup and Recovery para executar as seguintes tarefas relacionadas às cargas de trabalho do VMware:

* link:br-use-vmware-discovery.html["Descubra as cargas de trabalho da VMware"]
* link:br-use-vmware-protection-groups.html["Crie e gerencie grupos de proteção para cargas de trabalho do VMware"]
* link:br-use-vmware-backup.html["Fazer backup de cargas de trabalho do VMware"]
* link:br-use-vmware-restore.html["Restaurar cargas de trabalho do VMware"]

