---
sidebar: sidebar 
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: Crie manualmente backups sob demanda de aplicativos Kubernetes usando a interface web do NetApp Backup and Recovery. 
---
= Faça backup de um aplicativo Kubernetes usando a interface web do NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilize a interface web para realizar um backup sob demanda de uma aplicação Kubernetes.

*Função necessária do NetApp Console*

Superadministrador do NetApp Backup and Recovery ou administrador de backup do NetApp Backup and Recovery. link:reference-roles.html["Saiba mais sobre as funções de acesso do NetApp Backup and Recovery"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].



[[back-up-a-kubernetes-application]]
== Fazer backup de um aplicativo Kubernetes

Crie manualmente um backup de um aplicativo Kubernetes para estabelecer uma linha de base para futuros backups e snapshots ou para garantir que os dados mais recentes estejam protegidos.

.Passos
. No NetApp Backup and Recovery, selecione *Inventário*.
. Escolha uma instância do Kubernetes e selecione *Visualizar* para acessar os recursos associados a essa instância.
. Selecione a aba *Aplicativos*.
. Na lista de aplicativos, selecione um aplicativo do qual você deseja fazer backup e escolha o menu Ações associado.
. Selecione *Fazer backup agora*.
. Confirme se o aplicativo correto está selecionado.
. Selecione *Fazer backup*.


.Resultado
O Console cria um backup do aplicativo e exibe o progresso na área *Monitoramento* de Backup e Recuperação. O backup é criado com base na política de proteção associada ao aplicativo.
