---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: O NetApp Backup and Recovery permite que você gerencie informações de host de carga de trabalho, informações de banco de dados e informações de instâncias.  Você pode visualizar, editar e excluir configurações de proteção do seu inventário. 
---
= Adicionar e proteger aplicativos Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Backup and Recovery permite que você descubra facilmente seus clusters Kubernetes, sem gerar e carregar arquivos kubeconfig.  Você pode conectar clusters do Kubernetes e instalar o software necessário usando comandos simples copiados da interface do usuário do NetApp Console .

.Função necessária do NetApp Console
Administrador da organização ou administrador do SnapCenter . link:reference-roles.html["Saiba mais sobre as funções de acesso do NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^] .



== Adicionar e proteger um novo aplicativo Kubernetes

O primeiro passo para proteger aplicativos Kubernetes é criar um aplicativo no NetApp Backup and Recovery.  Ao criar um aplicativo, você torna o Console ciente do aplicativo em execução no cluster do Kubernetes.

.Antes de começar
Antes de poder adicionar e proteger um aplicativo Kubernetes, você precisalink:br-start-discover.html["descubra as cargas de trabalho do Kubernetes"] .

[role="tabbed-block"]
====
.Adicione um aplicativo usando a interface web
--
.Passos
. No NetApp Backup and Recovery, selecione *Inventário*.
. Escolha uma instância do Kubernetes e selecione *Exibir* para visualizar os recursos associados a essa instância.
. Selecione a aba *Aplicativos*.
. Selecione *Criar aplicativo*.
. Digite um nome para o aplicativo.
. Opcionalmente, escolha qualquer um dos seguintes campos para pesquisar os recursos que você deseja proteger:
+
** Cluster associado
** Espaços de nomes associados
** Tipos de recursos
** Seletores de rótulos


. Opcionalmente, selecione *Recursos com Escopo de Cluster* para escolher quaisquer recursos com escopo no nível do cluster. Se você incluí-los, eles serão adicionados ao aplicativo quando você o criar.
. Opcionalmente, selecione *Pesquisar* para encontrar os recursos com base nos seus critérios de pesquisa.
+

NOTE: O Console não armazena os parâmetros ou resultados da pesquisa; os parâmetros são usados para pesquisar no cluster Kubernetes selecionado recursos que podem ser incluídos no aplicativo.

. O Console exibe uma lista de recursos que correspondem aos seus critérios de pesquisa.
. Se a lista contiver os recursos que você deseja proteger, selecione *Avançar*.
. Opcionalmente, na área *Política*, escolha uma política de proteção existente para proteger o aplicativo ou crie uma nova. Se você não selecionar uma política, o aplicativo será criado sem uma política de proteção. Você podelink:br-use-policies-create.html#create-a-policy["adicionar uma política de proteção"] mais tarde.
. Na área *Prescrições e postscripts*, habilite e configure quaisquer ganchos de execução de prescrições ou postscripts que você deseja executar antes ou depois das operações de backup.  Para habilitar prescrições ou pós-escritos, você deve ter criado pelo menos umlink:br-use-manage-execution-hook-templates.html["modelo de gancho de execução"] .
. Selecione *Criar*.


.Resultado
O aplicativo é criado e aparece na lista de aplicativos na guia *Aplicativos* do inventário do Kubernetes.  O NetApp Console permite a proteção do aplicativo com base em suas configurações, e você pode monitorar o progresso na área *Monitoramento* de backup e recuperação.

--
.Adicionar um aplicativo usando um CR
--
.Passos
. Crie o arquivo CR do aplicativo de destino:
+
.. Crie o arquivo de recurso personalizado (CR) e dê um nome a ele (por exemplo, `my-app-name.yaml`).
.. Configurar os seguintes atributos:
+
*** *metadata.name*: (_Obrigatório_) O nome do recurso personalizado do aplicativo. Anote o nome escolhido, pois outros arquivos CR necessários para operações de proteção fazem referência a esse valor.
*** *spec.includedNamespaces*: (_Obrigatório_) Use o seletor de namespace e rótulo para especificar os namespaces e recursos que o aplicativo utiliza. O namespace do aplicativo deve fazer parte desta lista. O seletor de rótulo é opcional e pode ser usado para filtrar recursos dentro de cada namespace especificado.
*** *spec.includedClusterScopedResources*: (_Opcional_) Use este atributo para especificar recursos com escopo de cluster a serem incluídos na definição do aplicativo. Este atributo permite selecionar esses recursos com base em seu grupo, versão, tipo e rótulos.
+
**** *groupVersionKind*: (_Obrigatório_) Especifica o grupo de API, a versão e o tipo do recurso com escopo de cluster.
**** *labelSelector*: (Opcional) Filtra os recursos com escopo de cluster com base em seus rótulos.




.. Configurar as seguintes anotações, se necessário:
+
*** *metadata.annotations.protect.trident.netapp.io/skip-vm-freeze*: (_Opcional_) Esta anotação só se aplica a aplicações definidas a partir de máquinas virtuais, como em KubeVirt ambientes, onde o congelamento do sistema de arquivos ocorre antes dos snapshots. Especifique se esta aplicação pode gravar no sistema de arquivos durante um snapshot. Se definida como true, a aplicação ignora a configuração global e pode gravar no sistema de arquivos durante um snapshot. Se definida como false, a aplicação ignora a configuração global e o sistema de arquivos é congelado durante um snapshot. Se especificada, mas a aplicação não tiver máquinas virtuais na definição da aplicação, a anotação será ignorada. Se não especificada, a aplicação segue a link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["configuração global de congelamento do sistema de arquivos"].
*** *protect.trident.netapp.io/protection-command*: (opcional) Use esta anotação para instruir o NetApp Backup and Recovery a proteger ou parar de proteger o aplicativo. Os valores possíveis são `protect` ou `unprotect`.
*** *protect.trident.netapp.io/protection-policy-name*: (opcional) Use esta anotação para especificar o nome da política de proteção do NetApp Backup and Recovery que você deseja usar para proteger este aplicativo. Esta política de proteção já deve existir no NetApp Backup and Recovery.
+
[NOTE]
====
Se você precisar aplicar essa anotação depois que um aplicativo já tiver sido criado, pode usar o seguinte comando:

[source, console]
----
kubectl annotate application -n <application CR namespace> <application CR name> protect.trident.netapp.io/skip-vm-freeze="true"
----
====
+
Exemplo YAML:

+
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  annotations:
    protect.trident.netapp.io/skip-vm-freeze: "false"
    protect.trident.netapp.io/protection-command: "protect"
    protect.trident.netapp.io/protection-policy-name: "policy-name"
  name: my-app-name
  namespace: my-app-namespace
spec:
  includedNamespaces:
    - namespace: namespace-1
      labelSelector:
        matchLabels:
          app: example-app
    - namespace: namespace-2
      labelSelector:
        matchLabels:
          app: another-example-app
  includedClusterScopedResources:
    - groupVersionKind:
        group: rbac.authorization.k8s.io
        kind: ClusterRole
        version: v1
      labelSelector:
        matchLabels:
          mylabel: test
----




. (Opcional) Adicione filtragem que inclua ou exclua recursos marcados com rótulos específicos:
+
** *resourceFilter.resourceSelectionCriteria*: (obrigatório para filtragem) Use  `Include` ou  `Exclude` para incluir ou excluir um recurso definido em resourceMatchers. Adicione os seguintes parâmetros resourceMatchers para definir os recursos a serem incluídos ou excluídos:
+
*** *resourceFilter.resourceMatchers*: Uma matriz de objetos resourceMatcher. Se você definir vários elementos nesta matriz, eles correspondem como uma operação OR, e os campos dentro de cada elemento (group, kind, version) correspondem como uma operação AND.
+
**** *resourceMatchers[].group*: (_Opcional_) Grupo do recurso a ser filtrado.
**** *resourceMatchers[].kind*: (_Opcional_) Tipo do recurso a ser filtrado.
**** *resourceMatchers[].version*: (Opcional) Versão do recurso a ser filtrado.
**** *resourceMatchers[].names*: (_Opcional_) Nomes no campo metadata.name do Kubernetes do recurso a ser filtrado.
**** *resourceMatchers[].namespaces*: (_Opcional_) Namespaces no campo metadata.name do Kubernetes do recurso a ser filtrado.
**** *resourceMatchers[].labelSelectors*: (_Opcional_) String seletora de rótulo no campo metadata.name do Kubernetes do recurso, conforme definido no  https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["Documentação do Kubernetes"^]. Por exemplo: `"trident.netapp.io/os=linux"`.
+

NOTE: Quando ambos  `resourceFilter` e  `labelSelector` são usados,  `resourceFilter` é executado primeiro e, em seguida,  `labelSelector` é aplicado aos recursos resultantes.

+
Por exemplo:

+
[source, yaml]
----
spec:
  resourceFilter:
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
----






. Após criar a CR do aplicativo para corresponder ao seu ambiente, aplique a CR. Por exemplo:
+
[source, console]
----
kubectl apply -f my-app-name.yaml
----


--
====