---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: Comece a usar o NetApp Backup and Recovery verificando a prontidão do seu ambiente operacional, do agente do Console e da conta do Console.  Para usar o NetApp Backup and Recovery, você precisará destes pré-requisitos. 
---
= NetApp Backup and Recovery requisitos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de começar a usar NetApp Backup and Recovery, certifique-se de que seu NetApp Console e ambiente operacional atendam aos seguintes requisitos.



[[prepare-netapp-console]]
== Prepare o NetApp Console

Você acessa o NetApp Backup and Recovery por meio do NetApp Console. Para preparar o Console para o Backup and Recovery, você deve:

* Adicionar um agente de Console
* Adicione pelo menos um sistema de storage
* Configurar uma organização do Console e funções de usuário


Você precisa da função de administrador da organização ou superadministrador no NetApp Console para concluir esta preparação.

Para saber mais sobre NetApp Console, consulte  https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console para gerenciamento de storage unificado"^].



[[complete-initial-netapp-console-setup]]
=== Conclua a configuração inicial do NetApp Console

Conclua a configuração inicial do NetApp Console, caso ainda não o tenha feito.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Fluxo de trabalho de primeiros passos para NetApp Console (aplicativo SaaS)"^]



[[deploy-a-console-agent]]
=== Implantar um agente de Console

Um agente do Console é um componente de software leve que você instala em sua rede para conectar sua infraestrutura de storage ao NetApp Console. Ele permite orquestração avançada de storage, serviços de dados e integração segura com a nuvem.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Saiba mais sobre os agentes do Console"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["Implantar um agente de Console"^]



[[add-a-storage-system]]
=== Adicione um sistema de storage

Antes de poder proteger cargas de trabalho no NetApp Backup and Recovery, você precisa adicionar um sistema de storage ONTAP ao NetApp Console.

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Descubra clusters ONTAP locais no NetApp Console"^]



[[configure-an-organization-and-user-roles]]
=== Configurar uma organização e funções de usuário

Aprenda sobre organizações, projetos e funções de usuário e, em seguida, configure os usuários com as permissões apropriadas necessárias para executar suas tarefas.

Consulte  https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["Adicionar usuários a uma organização do NetApp Console"] para obter informações sobre como usar uma organização e projetos para controlar o acesso a recursos.

Consulte  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Funções de NetApp Backup and Recovery no ​​NetApp Console"] para obter detalhes sobre as funções e permissões necessárias para executar operações em NetApp Backup and Recovery.



[[requirements-for-backups-to-object-storage]]
== Requisitos para backups em storage de objetos

Para usar storage de objetos como destino de backup, você precisa de uma conta no AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID ou ONTAP e das permissões de acesso apropriadas configuradas.



[[requirements-for-protecting-ontap-volume-workloads]]
== Requisitos para proteger cargas de trabalho de volume do ONTAP

Para usar NetApp Backup and Recovery para cargas de trabalho de volume ONTAP, você precisa dos seguintes pré-requisitos de sistema host, espaço e dimensionamento.

* É necessário o ONTAP 9.8 ou posterior.
* ONTAP 9.12.1 ou posterior é necessário para a proteção de volumes FlexGroup. Consulte link:br-reference-limitations.html["Limitações conhecidas com o NetApp Backup and Recovery para volumes ONTAP"] para mais informações.
* ONTAP 9.17.1 ou posterior é necessário para fazer backup ou restaurar em storage de objetos compatível com S3.
* ONTAP 9.19.1 ou posterior é necessário para usar mais de 6 buckets por sistema em diferentes provedores de nuvem (até 100 buckets são suportados).
* Uma licença ONTAP One deve estar habilitada na instância ONTAP local.


Para obter informações sobre recursos compatíveis, tipos de volume, destinos de backup e restauração, e muito mais, consulte link:prev-ontap-protect-overview.html["Proteja seus dados de volume ONTAP"].



[[requirements-for-protecting-microsoft-sql-server-workloads]]
== Requisitos para proteger cargas de trabalho do Microsoft SQL Server

Para usar o NetApp Backup and Recovery para cargas de trabalho do Microsoft SQL Server, você precisa dos seguintes pré-requisitos de sistema host, espaço e dimensionamento.

[cols="33,66a"]
|===
| Item | Requisitos 


| Sistemas operacionais  a| 
Microsoft Windows Para obter as informações mais recentes sobre as versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .



| Versões do Microsoft SQL Server  a| 
A versão 2012 e posteriores são suportadas pelo VMware Virtual Machine File System (VMFS) e pelo VMware Virtual Machine Disk (VMDK) NFS.



| Versão do SnapCenter Server  a| 
O SnapCenter Server versão 5.0 ou superior é necessário se você for importar seus dados existentes do SnapCenter para o NetApp Backup and Recovery.


NOTE: Se você já tem o SnapCenter, primeiro verifique se atendeu aos pré-requisitos antes de importar do SnapCenter.  Verlink:concept-start-prereq-snapcenter-import.html["Pré-requisitos para importar recursos do SnapCenter"] .



| RAM mínima para o plug-in no host do SQL Server  a| 
1 GB



| Espaço mínimo de instalação e log para o plug-in no host do SQL Server  a| 
5 GB

Aloque espaço em disco suficiente e monitore o consumo de armazenamento pela pasta de logs.  O espaço de log necessário varia dependendo do número de backups realizados e da frequência das operações de proteção de dados.  Se não houver espaço suficiente, os logs não serão criados para as operações.



| Pacotes de software necessários  a| 
* ASP.NET Core Runtime 8.0.24 Hosting Bundle (e todos os patches 8.0.x subsequentes)
* PowerShell 7.4.13


Para obter as informações mais recentes sobre as versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .

|===
[cols="33,66a"]
|===
| Host do banco de dados | Storage suportado 


| Servidor físico  a| 
* LUNs apresentadas via Fibre Channel
* LUNs apresentadas via iSCSI




| VMware VM  a| 
* LUNs iSCSI conectados diretamente ao sistema convidado pelo iniciador iSCSI
* Sistemas de Arquivos de Máquina Virtual (VMFS)
* Datastores NFS




| Máquina virtual Hyper-V  a| 
LUNs iSCSI conectados diretamente ao sistema convidado pelo iniciador iSCSI


NOTE: A proteção de bancos de dados armazenados em discos pass-through ou arquivos VHD/VHDX provisionados no NetApp storage não é suportada.

|===


[[requirements-for-protecting-vmware-workloads]]
== Requisitos para proteger cargas de trabalho do VMware

Você precisa de requisitos específicos para descobrir e proteger suas cargas de trabalho do VMware.

|===
| Requisito | Suportado 


| Tipos de datastore | NFSv3, NFSv4.1 e VMFS 


| Versões do VMware ESXi Server | 7.0U1 e superior 


| Versões do VMware vCenter vSphere | 7.0U1 e superior 


| VMware Tools | O VMware Tools é necessário ao usar o recurso de restauração de arquivos e pastas e backups consistentes com a máquina virtual. Para garantir que a versão do VMware Tools seja compatível com a sua versão do ESXi Server, consulte o  https://packages.vmware.com/tools/versions["Informações de mapeamento de versão do VMware"]. 


| Tipos de endereço IP | IPv4, IPv6 


| Versões TLS do VMware | 1.2, 1.3 


| Armazenamento conectado  a| 
* ONTAP 9.13.1 ou posterior
* Amazon FSx for NetApp ONTAP storage systems executando a versão 9.13.1 ou posterior
* ASA r2 sistemas somente SAN (ONTAP 9.17.1 ou posterior necessário)


|===
[cols="33,66a"]
|===
| Tipo de porta | Porta pré-configurada 


| Porta do servidor VMware ESXi  a| 
443 (HTTPS), bidirecional. O recurso de restauração de arquivos e pastas utiliza esta porta.



| Cluster de armazenamento ou porta de VM de armazenamento  a| 
* 443 (HTTPS), bidirecional.
* 80 (HTTP), bidirecional. Esta porta é usada para comunicação entre o dispositivo virtual e a máquina virtual de armazenamento ou o cluster que contém a máquina virtual de armazenamento.


|===
.Requisitos de controle de acesso baseado em funções (RBAC) para proteger cargas de trabalho do VMware
Sua conta de usuário do Console precisa ter a função de superadministrador de NetApp Backup and Recovery para funcionar com cargas de trabalho do VMware.

Para obter mais informações sobre as funções de backup e recuperação, consulte  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Funções de backup e recuperação no NetApp Console"].



[[requirements-for-protecting-kvm-workloads]]
== Requisitos para proteger cargas de trabalho KVM

Você precisa de requisitos específicos para descobrir e proteger máquinas virtuais KVM.

* Uma distribuição Linux moderna executando a versão do kernel 5.14.0-503.22.1.el9_5.x86_64 (longo prazo) ou posterior
* Seus hosts KVM e máquinas virtuais devem ser gerenciados por uma plataforma de gerenciamento. O NetApp Backup and Recovery é compatível com as seguintes plataformas de gerenciamento:
+
** Apache CloudStack 4.22.0.0


* Certifique-se de que o tráfego de rede de entrada para a porta 22 seja permitido do agente do console para o host KVM.
* QEMU Guest Agent versão 9.0.0 ou posterior
* libvirt versão 10.5.0 ou posterior



NOTE: Para garantir que a restauração da carga de trabalho KVM seja concluída com sucesso, certifique-se de que a configuração *Habilitar snapshot consistente com a VM* esteja ativa na política de proteção usada para backups do KVM.

[NOTE]
====
Para habilitar a proteção de VMs KVM administradas por usuários não root, siga os passos abaixo:

. Monte o volume como tipo NFS3 para evitar o uso do `nobody` usuário e grupo.
. Use o seguinte comando para adicionar um usuário não root ao grupo. `qemu` grupo preservando seus grupos existentes:
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. Use o seguinte comando para conceder a propriedade do caminho de montagem ao `qemu` Usuário e grupo, e alterar permissões para o caminho de montagem:
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. Exclua o diretório NetApp_SnapCenter_Backups existente, caso esteja presente.


====


[[requirements-for-protecting-oracle-database-workloads]]
== Requisitos para proteger cargas de trabalho do Oracle Database

Garanta que seu ambiente atenda aos requisitos específicos para descobrir e proteger os recursos do Oracle Database.

|===
| Requisito | Suportado 


| Topologia de implantação  a| 
* Autônomo (NFS, SAN, ASM SAN)
* RAC sobre ASM (VMDK em VMFS)




| Versões do Oracle Database  a| 
* Oracle Database 19c
* Oracle Database 21c
* Banco de dados Oracle AI 26ai




| Armazenamento de banco de dados | Deve ser implementado no NetApp ONTAP (primário ou secundário) 


| OS do host  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| Armazenamento de objetos (destinos de backup)  a| 
* Armazenamento de Objetos do Azure
* Amazon AWS
* NetApp StorageGRID
* ONTAP S3


|===


[[requirements-for-protecting-kubernetes-applications]]
== Requisitos para proteger aplicativos Kubernetes

Você precisa de requisitos específicos para descobrir recursos do Kubernetes e proteger seus aplicativos Kubernetes.

Para os requisitos do NetApp Console, consulte <<Prepare o NetApp Console>>.


NOTE: NetApp recomenda fortemente atribuir um endereço IP estático ao agente do Console que você usa para cargas de trabalho do Kubernetes para evitar problemas caso o endereço IP do agente seja alterado.

* Um sistema ONTAP primário (sistemas ASA r2 não são suportados)
* NetApp Trident 25.02 ou posterior
* NetApp Trident Protect 26.05 ou posterior (instalado no cluster Kubernetes durante a descoberta)
* Um cluster Kubernetes - As distribuições e versões do Kubernetes suportadas incluem aquelas suportadas por https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"].
+
** Certifique-se de que a porta TCP 443 esteja desbloqueada na direção de saída entre o cluster Kubernetes, o Trident Protect Connector e o proxy Trident Protect.






[[requirements-for-protecting-hyper-v-workloads]]
== Requisitos para proteger cargas de trabalho do Hyper-V

Certifique-se de que sua instância do Hyper-V atenda aos requisitos específicos para descobrir e proteger máquinas virtuais.

|===
| Requisito | Suportado 


| Microsoft Hyper-V | 2019, 2022 e 2025 editions 


| ASP.NET Core Runtime | Pacote de hospedagem 8.0.24 (e todos os patches 8.0.x subsequentes) 


| PowerShell | 7.4.13 ou posterior 


| Se usuários sem privilégios de administrador forem proteger máquinas virtuais do Hyper-V, certifique-se de que eles tenham as seguintes permissões  a| 
* Membro do grupo de administradores locais
* Parte da política de segurança local "Log on as service"




| Certifique-se de que o tráfego HTTPS bidirecional esteja permitido para as seguintes portas nas configurações do Windows Firewall  a| 
* TCP 8144 (NetApp Plug-in para Hyper-V)
* TCP 8145 (NetApp Plug-in para Windows)




| Armazenamento conectado  a| 
* ONTAP 9.13.1 ou posterior
* Compartilhamentos SMB
* Armazenamento SAN conectado via iSCSI ou Fibre Channel


|===
.Requisitos de hardware para o host Hyper-V
* Hosts autônomos e agrupados pela FCI são suportados
* Mínimo de 1 GB de RAM para o plug-in NetApp Hyper-V no host Hyper-V
* 5 GB de espaço mínimo para instalação e log do plug-in no host Hyper-V
+

NOTE: Certifique-se de alocar espaço em disco suficiente no host Hyper-V para a pasta de logs e monitore regularmente seu uso.  O espaço necessário depende da frequência com que ocorrem backups e operações de proteção de dados.  Se não houver espaço suficiente, os logs não serão gerados.



.NetApp Requisitos de configuração do ONTAP
* Um sistema ONTAP primário (ONTAP 9.14.1 ou posterior)
* Para implementações do Hyper-V que utilizam compartilhamentos SMB para armazenar dados de máquinas virtuais, certifique-se de que a propriedade de compartilhamento de disponibilidade contínua esteja habilitada no sistema ONTAP. Consulte a  https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["Documentação do ONTAP"^] para obter instruções.

