---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com o NetApp NetApp Backup and Recovery. 
---
= Crie uma política para fazer backup de datastores no NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode criar uma política ou usar uma das seguintes políticas predefinidas disponíveis no NetApp Backup and Recovery.

[]
====
*NOTA* Para alternar entre cargas de trabalho de backup e recuperação do NetApp , consultelink:br-start-switch-ui.html["Alterne para diferentes cargas de trabalho do NetApp Backup and Recovery"] .

====
.Antes de começar
* Você deve criar políticas se não quiser editar as políticas predefinidas.
* Para mover backups do armazenamento de objetos para o armazenamento de arquivo, você deve executar o ONTAP 9.10.1 ou posterior e o Amazon Web Services ou o Microsoft Azure deve ser o provedor de nuvem.
* Você deve configurar o nível de acesso ao arquivo para cada provedor de nuvem.


.Sobre esta tarefa
As seguintes políticas predefinidas estão disponíveis no NetApp Console:

|===
| Nome da Política | Rótulo | Valor de retenção 


 a| 
LTR diário de 1 ano (retenção de longo prazo)
 a| 
Diário
 a| 
366



 a| 
5 anos de LTR diário
 a| 
Diário
 a| 
1830



 a| 
LTR semanal de 7 anos
 a| 
Semanalmente
 a| 
370



 a| 
LTR mensal de 10 anos
 a| 
Mensal
 a| 
120

|===
.Passos
. Na página Máquinas virtuais, na lista suspensa Configurações, selecione *Políticas*.
. Selecione *Criar política*.
. Na seção Detalhes da política, especifique o nome da política.
. Na seção Retenção, selecione um dos tipos de retenção e especifique o número de backups a serem retidos.
. Selecione Primário ou Secundário como fonte de armazenamento de backup.
. (Opcional) Se você quiser mover backups do armazenamento de objetos para o armazenamento de arquivamento após um determinado número de dias para otimização de custos, marque a caixa de seleção *Backups em camadas para arquivamento* e insira o número de dias após os quais o backup deve ser arquivado.
. Selecione *Criar*.
+

NOTE: Você não pode editar ou excluir uma política que esteja associada a um armazenamento de dados.


