---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com o NetApp NetApp Backup and Recovery. 
---
= Registre o SnapCenter Plug-in for VMware vSphere para usar com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve registrar o SnapCenter Plug-in for VMware vSphere no NetApp Backup and Recovery para que os datastores e máquinas virtuais sejam exibidos.  Somente um usuário com acesso administrativo pode registrar o SnapCenter Plug-in for VMware vSphere .

[]
====
*NOTA* Para alternar entre cargas de trabalho de backup e recuperação do NetApp , consultelink:br-start-switch-ui.html["Alterne para diferentes cargas de trabalho do NetApp Backup and Recovery"] .

====
.Passos
. Na interface do usuário do NetApp Console, selecione *Proteção* > *Backup e recuperação* > *Máquinas virtuais*.
. No menu suspenso *Configurações*, selecione * SnapCenter Plug-in for VMware vSphere*.
. Selecione *Registrar SnapCenter Plug-in for VMware vSphere*.
. Especifique os seguintes detalhes:
+
.. No campo SnapCenter Plug-in for VMware vSphere , especifique o FQDN ou endereço IP do host SnapCenter Plug-in for VMware vSphere .
.. No campo Porta, especifique o número da porta na qual o host do SnapCenter Plug-in for VMware vSphere está sendo executado.
+
Você deve garantir que a comunicação esteja aberta entre o host local do SnapCenter Plug-in for VMware vSphere , que está sendo executado na porta padrão 8144, e a instância do agente do Console, que pode estar sendo executada em qualquer provedor de nuvem (Amazon Web Services, Microsoft Azure, Google Cloud Platform) ou no local.

.. No campo Nome de usuário e Senha, especifique as credenciais do usuário do vCenter com a função de administrador.


. Selecione *Registrar*.


*Depois que você terminar*

Selecione *Backup e recuperação* > *Máquinas virtuais* para visualizar todos os armazenamentos de dados e máquinas virtuais que estão protegidos usando o SnapCenter Plug-in for VMware vSphere .
