---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: O NetApp Backup and Recovery oferece suporte a uma classe de armazenamento de arquivamento do Google e à maioria das regiões. 
---
= Camadas de armazenamento de arquivo do Google compatíveis com o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Backup and Recovery oferece suporte a uma classe de armazenamento de arquivamento do Google e à maioria das regiões.

[]
====

NOTE: Para alternar entre as versões da interface de usuário do NetApp Backup and Recovery , consultelink:br-start-switch-ui.html["Mudar para a interface de usuário anterior do NetApp Backup and Recovery"] .

====


== Classes de armazenamento de arquivamento do Google com suporte para NetApp Backup and Recovery

Quando os arquivos de backup são criados inicialmente, eles são armazenados no armazenamento _Padrão_.  Esta camada é otimizada para armazenar dados acessados com pouca frequência; mas isso também permite que você os acesse imediatamente.

Se o seu cluster local estiver usando o ONTAP 9.12.1 ou superior, você poderá optar por colocar backups mais antigos em camadas no armazenamento _Archive_ na interface do NetApp Backup and Recovery após um determinado número de dias (normalmente mais de 30 dias) para otimizar ainda mais os custos.  Os dados nessa camada exigirão um custo de recuperação mais alto, então você precisa considerar com que frequência precisará restaurar dados desses arquivos de backup arquivados.  Consulte a seção nesta página sobre restauração de dados do armazenamento de arquivo.

Observe que, ao configurar o NetApp Backup and Recovery com esse tipo de regra de ciclo de vida, você não deve configurar nenhuma regra de ciclo de vida ao configurar o bucket na sua conta do Google.

https://cloud.google.com/storage/docs/storage-classes["Saiba mais sobre as classes de armazenamento do Google"^].



== Restaurar dados do armazenamento de arquivo

Embora armazenar arquivos de backup mais antigos no armazenamento de arquivo seja muito mais barato do que o armazenamento padrão, acessar dados de um arquivo de backup no armazenamento de arquivo para operações de restauração levará um pouco mais de tempo e custará mais dinheiro.

Quanto custa restaurar dados do Google Archive?:: Para obter preços detalhados do Google Cloud Storage por região, visite o https://cloud.google.com/storage/pricing["Página de preços do Google Cloud Storage"^] .
Quanto tempo levará para restaurar meus objetos arquivados no Google Archive?:: Há 2 partes que compõem o tempo total de restauração:
+
--
* *Tempo de recuperação*: O tempo para recuperar o arquivo de backup do Archive e colocá-lo no armazenamento padrão.  Às vezes, isso é chamado de período de "reidratação".  Ao contrário das soluções de armazenamento "mais frias" fornecidas por outros provedores de nuvem, seus dados ficam acessíveis em milissegundos.
* *Tempo de restauração*: O tempo para restaurar os dados do arquivo de backup no armazenamento padrão.  Desta vez não é diferente da operação típica de restauração diretamente do armazenamento padrão, quando não se usa uma camada de arquivamento.


--

