---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database, dark site, private mode, restore database, backup and recovery, Console agent 
summary: 'Ao usar o NetApp Backup and Recovery em um site sem acesso à Internet, conhecido como "modo privado", os dados de configuração do NetApp Backup and Recovery são copiados para o bucket StorageGRID ou ONTAP S3 onde seus backups estão sendo armazenados.  Se você tiver um problema com o sistema host do agente do Console no futuro, poderá implantar um novo agente do Console e restaurar os dados críticos do NetApp Backup and Recovery.' 
---
= Restaurar dados de configuração do NetApp Backup and Recovery em um site escuro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao usar o NetApp Backup and Recovery em um site sem acesso à Internet, conhecido como _modo privado_, os dados de configuração do NetApp Backup and Recovery são copiados para o bucket StorageGRID ou ONTAP S3 onde seus backups estão sendo armazenados.  Se você tiver um problema com o sistema host do agente do Console, poderá implantar um novo agente do Console e restaurar os dados críticos do NetApp Backup and Recovery.


NOTE: Este procedimento se aplica somente aos dados de volume ONTAP .

Quando você usa o NetApp Backup and Recovery em um ambiente SaaS onde o agente do Console é implantado no seu provedor de nuvem ou no seu próprio sistema host que tem acesso à Internet, todos os dados importantes de configuração do NetApp Backup and Recovery são armazenados em backup e protegidos na nuvem.  Se você tiver um problema com o agente do Console, basta criar um novo agente do Console e adicionar seus sistemas e os detalhes do backup serão restaurados automaticamente.

Existem dois tipos de dados que são copiados:

* Banco de dados de backup e recuperação da NetApp - contém uma listagem de todos os volumes, arquivos de backup, políticas de backup e informações de configuração.
* Arquivos de catálogo indexados - contêm índices detalhados usados para a funcionalidade de pesquisa e restauração, tornando suas pesquisas muito rápidas e eficientes ao procurar dados de volume que você deseja restaurar.


É feito backup desses dados uma vez por dia à meia-noite, e no máximo 7 cópias de cada arquivo são retidas. Se o agente do Console estiver gerenciando vários sistemas ONTAP locais, os arquivos de backup e recuperação do NetApp estarão localizados no bucket do sistema que foi ativado primeiro.


TIP: Nenhum dado de volume é incluído no banco de dados do NetApp Backup and Recovery ou nos arquivos do Catálogo Indexado.



== Restaurar dados de backup e recuperação do NetApp para um novo agente do Console

Se o seu agente do Console local tiver uma falha catastrófica, você precisará instalar um novo agente do Console e restaurar os dados do NetApp Backup and Recovery para o novo agente do Console.

Você precisará executar as seguintes tarefas para retornar seu sistema NetApp Backup and Recovery a um estado de funcionamento:

* Instalar um novo agente do Console
* Restaurar o banco de dados de backup e recuperação do NetApp
* Restaurar os arquivos do catálogo indexado
* Redescubra todos os seus sistemas ONTAP locais e sistemas StorageGRID na interface de usuário do NetApp Console


Depois de verificar se seu sistema está funcionando novamente, recomendamos que você crie novos arquivos de backup.

.O que você vai precisar
Você precisará acessar os backups de banco de dados e índice mais recentes do bucket StorageGRID ou ONTAP S3 onde seus arquivos de backup estão sendo armazenados:

* Arquivo de banco de dados MySQL do NetApp Backup and Recovery
+
Este arquivo está localizado no seguinte local no bucket `netapp-backup-<GUID>/mysql_backup/` , e é chamado `CBS_DB_Backup_<day>_<month>_<year>.sql` .

* Arquivo zip de backup do catálogo indexado
+
Este arquivo está localizado no seguinte local no bucket `netapp-backup-<GUID>/catalog_backup/` , e é chamado `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip` .





=== Instalar um novo agente de console em um novo host Linux local

Ao instalar um novo agente do Console, certifique-se de baixar a mesma versão do software que você instalou no agente do Console original.  Alterações periódicas na estrutura do banco de dados do NetApp Backup and Recovery podem tornar as versões mais recentes do software incompatíveis com os backups originais do banco de dados. Você pode https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["atualize o software do agente do Console para a versão mais atual após restaurar o banco de dados de backup"^] .

. https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["Instale o agente do Console em um novo host Linux local"^]
. Efetue login no Console usando as credenciais de usuário administrador que você acabou de criar.




=== Restaurar o banco de dados de backup e recuperação do NetApp

. Copie o backup do MySQL do local de backup para o novo host do agente do Console. Usaremos o nome de arquivo de exemplo "CBS_DB_Backup_23_05_2023.sql" abaixo.
. Copie o backup para o contêiner Docker do MySQL usando um dos seguintes comandos, dependendo se você estiver usando um contêiner Docker ou Podman:
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Entre no shell do contêiner MySQL usando um dos seguintes comandos, dependendo se você estiver usando um contêiner Docker ou Podman:
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. No shell do contêiner, implante o "env".
. Você precisará da senha do banco de dados MySQL, então copie o valor da chave "MYSQL_ROOT_PASSWORD".
. Restaure o banco de dados MySQL do NetApp Backup and Recovery usando o seguinte comando:
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. Verifique se o NetApp Backup and Recovery MySQL DB foi restaurado corretamente usando os seguintes comandos SQL:
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
Digite a senha.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
Verifique se os volumes exibidos são os mesmos que existiam no seu ambiente original.





=== Restaurar os arquivos do catálogo indexado

. Copie o arquivo zip de backup do Catálogo Indexado (usaremos o nome de arquivo de exemplo "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip") do local de backup para o novo host do agente do Console na pasta "/opt/application/netapp/cbs".
. Descompacte o arquivo "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip" usando o seguinte comando:
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. Execute o comando *ls* para garantir que a pasta "catalogdb1" foi criada com as subpastas "changes" e "snapshots" abaixo.




=== Descubra seus clusters ONTAP e sistemas StorageGRID

. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["Descubra todos os sistemas ONTAP on-prem"^]que estavam disponíveis no seu ambiente anterior. Isso inclui o sistema ONTAP que você usou como servidor S3.
. https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["Descubra seus sistemas StorageGRID"^] .




=== Configurar os detalhes do ambiente StorageGRID

Adicione os detalhes do sistema StorageGRID associado aos seus sistemas ONTAP conforme eles foram configurados na configuração original do agente do Console usando o https://docs.netapp.com/us-en/console-automation/index.html["APIs do console NetApp"^] .

As informações a seguir se aplicam a instalações em modo privado a partir do NetApp Console 3.9.xx. Para versões mais antigas, use o seguinte procedimento: https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite Cloud Backup: backup e restauração de MySQL e catálogo indexado"^] .

Você precisará executar essas etapas para cada sistema que estiver fazendo backup de dados no StorageGRID.

. Extraia o token de autorização usando a seguinte API oauth/token.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
Embora o endereço IP, o nome de usuário e as senhas sejam valores personalizados, o nome da conta não é. O nome da conta é sempre "account-DARKSITE1". Além disso, o nome de usuário deve usar um nome no formato de e-mail.

+
Esta API retornará uma resposta como a seguinte. Você pode recuperar o token de autorização conforme mostrado abaixo.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Extraia o ID do sistema e o X-Agent-Id usando a API tenancy/external/resource.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
Esta API retornará uma resposta como a seguinte. O valor em "resourceIdentifier" denota o _WorkingEnvironment Id_ e o valor em "agentId" denota _x-agent-id_.

. Atualize o banco de dados do NetApp Backup and Recovery com os detalhes do sistema StorageGRID associado aos sistemas. Certifique-se de inserir o Nome de Domínio Totalmente Qualificado do StorageGRID, bem como a Chave de Acesso e a Chave de Armazenamento, conforme mostrado abaixo:
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== Verifique as configurações de backup e recuperação do NetApp

. Selecione cada sistema ONTAP e clique em *Exibir backups* ao lado do serviço de backup e recuperação no painel direito.
+
Você poderá ver todos os backups que foram criados para seus volumes.

. No Painel de restauração, na seção Pesquisar e restaurar, clique em *Configurações de indexação*.
+
Certifique-se de que os sistemas que tinham a Catalogação Indexada habilitada anteriormente permaneçam habilitados.

. Na página Pesquisar e restaurar, execute algumas pesquisas de catálogo para confirmar se a restauração do catálogo indexado foi concluída com sucesso.

