---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Crie um certificado de segurança para permitir a comunicação entre o NetApp Backup and Recovery e o StorageGRID ou ONTAP. 
---
= Configure os certificados da Autoridade de Certificação (CA) para o NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configure os certificados da Autoridade de Certificação (CA) para que o NetApp Backup and Recovery possa validar conexões seguras com o StorageGRID ou o ONTAP. Siga as etapas que se aplicam ao seu ambiente e aos sistemas que você deseja proteger.



[[create-a-ca-certificate-for-storagegrid]]
== Crie um certificado CA para o StorageGRID

Se a comunicação entre os contêineres do NetApp Backup and Recovery e o StorageGRID deve verificar o certificado do StorageGRID, siga as etapas abaixo.

O certificado gerado deve usar o mesmo nome comum (CN) e nome alternativo do assunto que você forneceu no NetApp Backup and Recovery ao ativar o backup.

.Passos
. Siga as etapas na documentação do StorageGRID para criar o certificado do StorageGRID .
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["Informações do StorageGRID sobre a configuração de certificados"]

. Atualize o StorageGRID com o certificado, caso ainda não tenha feito isso.
. Faça login no agente do Console como usuário raiz. Execute:
+
[source, shell]
----
sudo su
----
. Localize o volume Docker do NetApp Backup and Recovery (Cloud Backup Service). Execute:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Exemplo de saída:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: O nome do volume difere entre os modos de implantação Padrão, Privado e Restrito. Este exemplo usa o modo Padrão. Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

. Localize o ponto de montagem do volume do NetApp Backup and Recovery . Correr:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Exemplo de saída:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: O ponto de montagem difere entre os modos de implantação Padrão, Privado e Restrito. Este exemplo mostra uma implantação de nuvem padrão. Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

. Acesse o diretório do ponto de montagem. Execute:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Se o certificado do StorageGRID for assinado pela CA raiz e por uma CA intermediária, anexe ambos os  `pem` arquivos em um único arquivo chamado  `sgws.crt` no local atual. Não adicione o certificado folha a este arquivo.




[[steps-for-the-cloudmanagercbs-container]]
=== Etapas para o contêiner cloudmanager_cbs

Ative a verificação do certificado do servidor StorageGRID em NetApp Backup and Recovery (Cloud Backup Service).

. Altere para o volume Docker que você encontrou nas etapas anteriores.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Altere para o diretório de configuração.
+
[source, shell]
----
cd cbs_config
----
. Crie e salve um arquivo de configuração conforme mostrado abaixo, com um dos seguintes nomes, com base no seu ambiente de implantação:
+
** `production-customer.json` para implantações nos modos Padrão e Restrito
** `darksite-customer.json` para implantações em modo privado
+
Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

+
*Arquivo de configuração*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Saia do contêiner. Correr:
+
[source, shell]
----
exit
----
. Reiniciar `cloudmanager_cbs` . Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Etapas para o contêiner cloudmanager_cbs_catalog

Em seguida, habilite a verificação do certificado do servidor StorageGRID para o Serviço de Catalogação.

. Altere para o volume do Docker:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Configurar o catálogo. Correr:
+
[source, shell]
----
cd cbs_catalog_config
----
. Crie um arquivo de configuração conforme mostrado abaixo com um dos seguintes nomes, com base no seu ambiente de implantação:
+
** `production-customer.json` para implantações nos modos Padrão e Restrito
** `darksite-customer.json` para implantações em modo privado
+
Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

+
*Arquivo de configuração do catálogo*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Reinicie o catálogo. Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[update-the-console-agent-certificate-with-the-storagegrid-certificate-based-on-the-agent-operating-system]]
=== Atualizar o certificado do agente do Console com o certificado StorageGRID com base no sistema operacional do agente



==== Ubuntu

. Copie o certificado SGWS para  `/usr/local/share/ca-certificates`. Aqui está um exemplo:
+
[source, shell]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
onde `sgws.crt` é o certificado da CA raiz.

. Atualize os certificados do host com o certificado do StorageGRID. Execute:
+
[source, shell]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Copie o certificado SGWS para `/etc/pki/ca-trust/source/anchors/` .
+
[source, shell]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
onde `sgws.crt` é o certificado da CA raiz.

. Atualize os certificados do host com o certificado StorageGRID .
+
[source, shell]
----
update-ca-trust extract
----
. Atualizar o `ca-bundle.crt`
+
[source, shell]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Para verificar se os certificados estão presentes, execute o seguinte comando:
+
[source, shell]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




[[create-a-ca-certificate-for-ontap]]
== Crie um certificado CA para o ONTAP

Se a comunicação entre os contêineres do NetApp Backup and Recovery e o ONTAP deve validar o certificado do ONTAP, conclua as etapas a seguir.

NetApp Backup and Recovery usa o endereço IP de gerenciamento do cluster para se conectar ao ONTAP. Insira o endereço IP do cluster nos campos de Nome Alternativo do Assunto do certificado. Especifique esse valor ao gerar a CSR no System Manager.

Use a documentação do System Manager para criar um novo certificado CA para o ONTAP.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Gerenciar certificados com o Gerenciador de Sistemas"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["Como gerenciar certificados SSL ONTAP com o System Manager"]


.Passos
. Faça login no agente do Console como root. Execute:
+
[source, shell]
----
sudo su
----
. Localize o volume Docker do NetApp Backup and Recovery. Execute:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Exemplo de saída:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: O nome do volume difere entre os modos de implantação Padrão, Privado e Restrito. Este exemplo mostra uma implantação de nuvem padrão. Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

. Localize o ponto de montagem do volume. Execute:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Exemplo de saída:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: O ponto de montagem difere entre os modos de implantação Padrão, Privado e Restrito. Este exemplo mostra uma implantação de nuvem padrão. Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

. Acesse o diretório do ponto de montagem. Execute:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Conclua uma das seguintes etapas:
+
** Se o certificado ONTAP for assinado pela CA raiz e uma CA intermediária, anexe o `pem` arquivos de ambos em um arquivo chamado `ontap.crt` no local atual.
** Se o certificado ONTAP for assinado por uma única CA, renomeie o `pem` arquivar como `ontap.crt` e copie-o no local atual. Não adicione o certificado de folha a este arquivo.






[[steps-for-the-cloudmanagercbs-container]]
=== Etapas para o contêiner cloudmanager_cbs

Em seguida, habilite a verificação do certificado do servidor ONTAP no NetApp Backup and Recovery (Cloud Backup Service).

. Altere para o volume Docker que você encontrou nas etapas anteriores.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Mude para o diretório de configuração. Correr:
+
[source, shell]
----
cd cbs_config
----
. Crie um arquivo de configuração conforme mostrado abaixo com um dos seguintes nomes, com base no seu ambiente de implantação:
+
** `production-customer.json` para implantações nos modos Padrão e Restrito
** `darksite-customer.json` para implantações em modo privado
+
Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

+
*Arquivo de configuração*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Saia do contêiner. Correr:
+
[source, shell]
----
exit
----
. Reinicie o NetApp Backup and Recovery. Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Etapas para o contêiner cloudmanager_cbs_catalog

Ative a verificação de certificado do servidor ONTAP para o Serviço de Catalogação.

. Altere para o volume do Docker. Execute:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Correr:
+
[source, shell]
----
cd cbs_catalog_config
----
. Crie um arquivo de configuração conforme mostrado abaixo com um dos seguintes nomes, com base no seu ambiente de implantação:
+
** `production-customer.json` para implantações nos modos Padrão e Restrito
** `darksite-customer.json` para implantações em modo privado
+
Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"] .

+
*Arquivo de configuração*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Reinicie o NetApp Backup and Recovery. Correr:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[create-a-certificate-for-both-ontap-and-storagegrid]]
== Crie um certificado para ONTAP e StorageGRID

Se você precisar habilitar o certificado para ONTAP e StorageGRID, o arquivo de configuração ficará assim:

*Arquivo de configuração para ONTAP e StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----