= Modos de proteção SnapLock Compliance e SnapLock Enterprise
:allow-uri-read: 




[[snaplock-compliance-and-snaplock-enterprise-protection-modes]]
=== Modos de proteção SnapLock Compliance e SnapLock Enterprise

NetApp Backup and Recovery agora pode fazer backup de volumes FlexVol e FlexGroup locais que estão configurados usando os modos de proteção SnapLock Compliance ou SnapLock Enterprise. Seus clusters devem estar executando ONTAP 9.14 ou posterior para esse suporte. O backup de volumes FlexVol no modo SnapLock Enterprise é suportado desde o ONTAP 9.11.1. Versões anteriores do ONTAP não oferecem suporte ao backup de volumes protegidos por SnapLock.

Consulte a lista completa de volumes suportados em  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Saiba mais sobre o NetApp Backup and Recovery"].



[[indexing-for-search-restore-process-on-volumes-page]]
=== Indexação para processo de Pesquisa e Restauração na página Volumes

Antes de poder usar a Pesquisa e Restauração, você precisa habilitar a "Indexação" em cada sistema de origem do qual deseja restaurar dados de volume.  Isso permite que o Catálogo Indexado rastreie os arquivos de backup de cada volume.  A página Volumes agora mostra o status de indexação:

* Indexado: Os volumes foram indexados.
* Em andamento: a indexação está em andamento.
* Não indexado: a indexação ainda não foi iniciada.
* Indexação pausada: a indexação está pausada.
* Erro: ocorreu um erro de indexação.
* Não ativado: a indexação não está ativada para esta fonte.

