= Aprimoramento das cargas de trabalho do ONTAP Volumes
:allow-uri-read: 




[[ontap-volumes-workloads-enhancement]]
=== Aprimoramento das cargas de trabalho do ONTAP Volumes

Nesta versão, o ONTAP Volumes introduz a seguinte melhoria em versão prévia para cargas de trabalho:

*Suporte aprimorado para dark sites*: o NetApp Backup and Recovery para dark sites agora oferece os mesmos recursos de proteção de dados do ONTAP Volumes que o NetApp Backup and Recovery. Esse aprimoramento inclui serviços atualizados de backup, restauração e gerenciamento de tarefas, além de um novo banco de dados de metadados. Durante uma atualização, os dados existentes do banco de dados são preservados e migrados automaticamente. Após a atualização, revise os logs de auditoria para verificar se a migração foi concluída com sucesso. O NetApp Backup and Recovery para dark sites oferece suporte apenas a cargas de trabalho do ONTAP Volumes.

Para obter detalhes sobre como proteger as cargas de trabalho do ONTAP Volumes, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Saiba mais sobre a proteção de volumes do ONTAP com NetApp Backup e Recuperação"].



[[kubernetes-workloads-enhancements]]
=== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Trident Protect 26.09*: Esta versão inclui Trident Protect 26.09.
* *Controle de acesso baseado em funções (RBAC) granular por cluster e namespace*: durante a descoberta de clusters do Kubernetes, você pode controlar o acesso aos recursos selecionando um projeto ou pasta para associar ao novo cluster. Você também pode registrar namespaces específicos para controle de acesso. Isso permite um controle de acesso mais granular no nível do cluster ou do namespace.
* *Restaurar arquivos e pastas*: Agora você pode restaurar ou baixar arquivos e pastas específicos de backups de aplicativos baseados em máquinas virtuais do Kubernetes.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Saiba mais sobre como proteger cargas de trabalho do Kubernetes com NetApp Backup and Recovery"].
