= Aprimoramentos de cargas de trabalho do Kubernetes
:allow-uri-read: 




=== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Suporte nativo para proteção de VMs*: Agora você pode criar aplicativos baseados em VMs, permitindo proteger máquinas virtuais da mesma forma que protege qualquer outro aplicativo.
* *Transformações de recursos*: Agora você pode usar transformações de recursos e modelos de transformação de recursos para adicionar, remover e modificar atributos de recursos durante o processo de restauração.
* *Atualize o Trident Protect a partir do Backup and Recovery*: Agora você pode atualizar o Trident Protect para um cluster Kubernetes diretamente a partir do Backup and Recovery.
* *Visualizar recursos protegidos*: Agora você pode visualizar os recursos incluídos em cada ponto de recuperação de um aplicativo e baixar um relatório JSON detalhado. Isso oferece visibilidade completa dos seus pontos de recuperação e simplifica a conformidade com auditorias.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral das cargas de trabalho do Protect Kubernetes"] .
