= Aprimoramentos nas cargas de trabalho do ONTAP Volumes
:allow-uri-read: 




=== Aprimoramentos nas cargas de trabalho do ONTAP Volumes

Nesta versão, as cargas de trabalho do ONTAP Volumes introduzem a seguinte melhoria:

*Suporte para storage de nuvem compatível com S3*: NetApp Backup and Recovery para cargas de trabalho de Volumes agora oferece suporte a backup em storage de nuvem compatível com S3.

Para obter detalhes sobre como proteger as cargas de trabalho do ONTAP Volumes, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Visão geral das cargas de trabalho do Protect ONTAP Volumes"].



=== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, as cargas de trabalho do Hyper-V introduzem as seguintes melhorias:

* *Aprimoramentos na restauração de arquivos e pastas para uma máquina virtual convidada*: Agora você pode restaurar arquivos e pastas de um snapshot no storage primário ou secundário para uma máquina virtual Windows convidada. Esse recurso agora é compatível com VMs CIFS e SAN.


Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Visão geral das cargas de trabalho de proteção do Hyper-V"] .
