= Aprimoramentos nas cargas de trabalho do Hyper-V
:allow-uri-read: 




=== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, as cargas de trabalho do Hyper-V introduzem as seguintes melhorias:

* *Proteja VMs em armazenamento SAN*: Agora você pode proteger VMs em armazenamento SAN de objetos.
* *Aprimoramentos na restauração para local alternativo*: Agora você pode restaurar para um local alternativo a partir dos locais primário e secundário para VMs em storage SAN.
* *Restaurar arquivos e pastas para uma VM convidada*: Agora você pode restaurar arquivos e pastas de um Snapshot no storage primário para uma VM Windows convidada. Essa funcionalidade é compatível apenas com VMs CIFS.


Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Visão geral das cargas de trabalho de proteção do Hyper-V"] .



=== Aprimoramentos nas cargas de trabalho do KVM

Nesta versão, as cargas de trabalho KVM introduzem a seguinte melhoria:

*Restaurar para local alternativo*: Agora você pode restaurar VMs KVM para um destino alternativo (este recurso agora está disponível para todos).

Para obter detalhes sobre como proteger cargas de trabalho KVM, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Visão geral das cargas de trabalho de proteção do KVM"] .



=== Aprimoramentos nas cargas de trabalho do Oracle Database

Nesta versão, as cargas de trabalho do Oracle Database introduzem as seguintes melhorias:

* *Suporte ao Oracle AI Database 26ai*: NetApp Backup and Recovery agora é compatível com o Oracle AI Database 26ai.
* *Suporte para verificação de backup*: Agora você pode configurar políticas de backup para verificar automaticamente a integridade dos seus backups do banco de dados Oracle.


Para obter detalhes sobre como proteger cargas de trabalho do Oracle Database, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Visão geral da proteção de cargas de trabalho do Oracle Database"].



=== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta as seguintes melhorias:

* *Suporte a datastores abrangentes para grupos de proteção*: Agora você pode escolher o comportamento dos grupos de proteção ao proteger máquinas virtuais cujos discos virtuais abrangem vários datastores.
* *Suporte a clonagem*: Agora você pode criar clones de snapshots de máquinas virtuais a partir do storage primário e secundário.


Para obter detalhes sobre como proteger cargas de trabalho do VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral das cargas de trabalho do Protect VMware"] .
