= Anotação de tempo limite do data mover
:allow-uri-read: 




== Anotação de tempo limite do data mover

Use a anotação  `protect.trident.netapp.io/data-mover-timeout-sec` para definir um tempo limite por operação de movimentação de dados (em segundos) durante backup e restauração. Ela especifica quanto tempo um data mover aguarda o progresso de uma operação antes de atingir o tempo limite. Isso é útil para detectar e lidar com transferências interrompidas (por exemplo, quando problemas de rede impedem o progresso da restauração de dados do volume).

Você pode usar essa anotação em seu arquivo YAML conforme mostrado abaixo:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
Neste exemplo, a anotação falha na operação `BackupRestore` se não houver progresso dentro de 2 segundos na operação de restauração.


NOTE: Se o valor da anotação for menor ou igual a 0, a operação falhará imediatamente.
