= Anotações e rótulos de namespace durante operações de restauração e failover
:allow-uri-read: 




[[namespace-annotations-and-labels-during-restore-and-failover-operations]]
== Anotações e rótulos de namespace durante operações de restauração e failover

Durante a restauração e o failover, os rótulos e anotações do namespace de destino são atualizados para corresponder à origem: as chaves da origem são adicionadas ou substituem as chaves de destino, enquanto as chaves que existem apenas no destino permanecem inalteradas.


NOTE: No Red Hat OpenShift, as anotações de namespace são importantes porque garantem que os pods restaurados recebam as restrições e permissões de contexto de segurança corretas, permitindo que acessem volumes e sejam executados sem erros de permissão. Para obter mais informações, consulte a link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift security context constraints documentação"^].

Defina a variável de ambiente do Kubernetes

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
Antes da restauração ou failover, para evitar que anotações específicas do namespace de destino sejam sobrescritas. Por exemplo:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Durante a restauração ou failover, quaisquer anotações e rótulos de namespace especificados em `restoreSkipNamespaceAnnotations` e `restoreSkipNamespaceLabels` são excluídos da operação de restauração ou failover. Certifique-se de que essas configurações sejam definidas durante a instalação inicial do Helm. Para saber mais, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Configurar configurações adicionais do helm chart do Trident Protect"].

Se você usou o Helm com a  `--create-namespace` flag para instalar o aplicativo de origem, Trident Protect copia o rótulo de nome para o namespace de destino. Se o valor do rótulo corresponder ao nome do namespace de origem, ele será substituído pelo nome do namespace de destino; caso contrário, permanecerá como está.



[[example]]
=== Exemplo

O exemplo a seguir mostra namespaces de origem e destino com rótulos e anotações diferentes, e exibe o namespace de destino antes e depois da operação para ilustrar como as chaves são adicionadas, mescladas ou sobrescritas.



==== Antes da operação de restauração ou failover

A tabela a seguir ilustra o estado dos namespaces de origem e destino do exemplo antes da operação de restauração ou failover:

[cols="1,2a,2a"]
|===
| Espaço de nomes | Anotações | Etiquetas 


| Namespace ns-1 (fonte)  a| 
* annotation.one/key: "valoratualizado"
* anotação.dois/chave: "true"

 a| 
* ambiente=produção
* compliance=hipaa
* name=ns-1




| Espaço de nomes ns-2 (destino)  a| 
* annotation.one/key: "true"
* anotação.three/chave: "falso"

 a| 
* role=database


|===


==== Após a operação de restauração

A tabela a seguir ilustra o estado do namespace de destino de exemplo após a operação de restauração ou failover. Algumas chaves foram adicionadas, outras foram sobrescritas e o  `name` rótulo foi atualizado para corresponder ao namespace de destino:

[cols="1,2a,2a"]
|===
| Espaço de nomes | Anotações | Etiquetas 


| Espaço de nomes ns-2 (destino)  a| 
* annotation.one/key: "valoratualizado"
* anotação.dois/chave: "true"
* anotação.three/chave: "falso"

 a| 
* name=ns-2
* compliance=hipaa
* ambiente=produção
* role=database


|===