= AnotaĂ§Ă”es e rĂłtulos de namespace durante operaĂ§Ă”es de restauraĂ§ĂŁo e failover
:allow-uri-read: 




== AnotaĂ§Ă”es e rĂłtulos de namespace durante operaĂ§Ă”es de restauraĂ§ĂŁo e failover

Durante a restauraĂ§ĂŁo e o failover, os rĂłtulos e anotaĂ§Ă”es do namespace de destino sĂŁo atualizados para corresponder Ă  origem: as chaves da origem sĂŁo adicionadas ou substituem as chaves de destino, enquanto as chaves que existem apenas no destino permanecem inalteradas.


NOTE: No Red Hat OpenShift, as anotaĂ§Ă”es de namespace sĂŁo importantes porque garantem que os pods restaurados recebam as restriĂ§Ă”es e permissĂ”es de contexto de seguranĂ§a corretas, permitindo que acessem volumes e sejam executados sem erros de permissĂŁo. Para obter mais informaĂ§Ă”es, consulte a link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift security context constraints documentaĂ§ĂŁo"^].

Defina a variĂĄvel de ambiente do Kubernetes

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
Antes da restauraĂ§ĂŁo ou failover, para evitar que anotaĂ§Ă”es especĂ­ficas do namespace de destino sejam sobrescritas. Por exemplo:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Durante a restauraĂ§ĂŁo ou failover, quaisquer anotaĂ§Ă”es e rĂłtulos de namespace especificados em `restoreSkipNamespaceAnnotations` e `restoreSkipNamespaceLabels` sĂŁo excluĂ­dos da operaĂ§ĂŁo de restauraĂ§ĂŁo ou failover. Certifique-se de que essas configuraĂ§Ă”es sejam definidas durante a instalaĂ§ĂŁo inicial do Helm. Para saber mais, consulte https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Configurar configuraĂ§Ă”es adicionais do helm chart do Trident Protect"].

Se vocĂȘ usou o Helm com a  `--create-namespace` flag para instalar o aplicativo de origem, Trident Protect copia o rĂłtulo de nome para o namespace de destino. Se o valor do rĂłtulo corresponder ao nome do namespace de origem, ele serĂĄ substituĂ­do pelo nome do namespace de destino; caso contrĂĄrio, permanecerĂĄ como estĂĄ.



=== Exemplo

O exemplo a seguir mostra namespaces de origem e destino com rĂłtulos e anotaĂ§Ă”es diferentes, e exibe o namespace de destino antes e depois da operaĂ§ĂŁo para ilustrar como as chaves sĂŁo adicionadas, mescladas ou sobrescritas.



==== Antes da operaĂ§ĂŁo de restauraĂ§ĂŁo ou failover

A tabela a seguir ilustra o estado dos namespaces de origem e destino do exemplo antes da operaĂ§ĂŁo de restauraĂ§ĂŁo ou failover:

[cols="1,2a,2a"]
|===
| EspaĂ§o de nomes | AnotaĂ§Ă”es | Etiquetas 


| Namespace ns-1 (fonte)  a| 
* annotation.one/key: "valoratualizado"
* anotaĂ§ĂŁo.dois/chave: "true"

 a| 
* ambiente=produĂ§ĂŁo
* compliance=hipaa
* name=ns-1




| EspaĂ§o de nomes ns-2 (destino)  a| 
* annotation.one/key: "true"
* anotaĂ§ĂŁo.three/chave: "falso"

 a| 
* role=database


|===


==== ApĂłs a operaĂ§ĂŁo de restauraĂ§ĂŁo

A tabela a seguir ilustra o estado do namespace de destino de exemplo apĂłs a operaĂ§ĂŁo de restauraĂ§ĂŁo ou failover. Algumas chaves foram adicionadas, outras foram sobrescritas e o  `name` rĂłtulo foi atualizado para corresponder ao namespace de destino:

[cols="1,2a,2a"]
|===
| EspaĂ§o de nomes | AnotaĂ§Ă”es | Etiquetas 


| EspaĂ§o de nomes ns-2 (destino)  a| 
* annotation.one/key: "valoratualizado"
* anotaĂ§ĂŁo.dois/chave: "true"
* anotaĂ§ĂŁo.three/chave: "falso"

 a| 
* name=ns-2
* compliance=hipaa
* ambiente=produĂ§ĂŁo
* role=database


|===